// Code generated by protoc-gen-go. DO NOT EDIT.
// source: food/messages.proto

package food

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FoodGenre struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodGenre) Reset()         { *m = FoodGenre{} }
func (m *FoodGenre) String() string { return proto.CompactTextString(m) }
func (*FoodGenre) ProtoMessage()    {}
func (*FoodGenre) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{0}
}

func (m *FoodGenre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodGenre.Unmarshal(m, b)
}
func (m *FoodGenre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodGenre.Marshal(b, m, deterministic)
}
func (m *FoodGenre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodGenre.Merge(m, src)
}
func (m *FoodGenre) XXX_Size() int {
	return xxx_messageInfo_FoodGenre.Size(m)
}
func (m *FoodGenre) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodGenre.DiscardUnknown(m)
}

var xxx_messageInfo_FoodGenre proto.InternalMessageInfo

func (m *FoodGenre) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FoodGenre) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FoodRecord struct {
	Id                   uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *FoodData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FoodRecord) Reset()         { *m = FoodRecord{} }
func (m *FoodRecord) String() string { return proto.CompactTextString(m) }
func (*FoodRecord) ProtoMessage()    {}
func (*FoodRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{1}
}

func (m *FoodRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodRecord.Unmarshal(m, b)
}
func (m *FoodRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodRecord.Marshal(b, m, deterministic)
}
func (m *FoodRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodRecord.Merge(m, src)
}
func (m *FoodRecord) XXX_Size() int {
	return xxx_messageInfo_FoodRecord.Size(m)
}
func (m *FoodRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodRecord.DiscardUnknown(m)
}

var xxx_messageInfo_FoodRecord proto.InternalMessageInfo

func (m *FoodRecord) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FoodRecord) GetData() *FoodData {
	if m != nil {
		return m.Data
	}
	return nil
}

type FoodData struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                uint64     `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Genre                *FoodGenre `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FoodData) Reset()         { *m = FoodData{} }
func (m *FoodData) String() string { return proto.CompactTextString(m) }
func (*FoodData) ProtoMessage()    {}
func (*FoodData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{2}
}

func (m *FoodData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodData.Unmarshal(m, b)
}
func (m *FoodData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodData.Marshal(b, m, deterministic)
}
func (m *FoodData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodData.Merge(m, src)
}
func (m *FoodData) XXX_Size() int {
	return xxx_messageInfo_FoodData.Size(m)
}
func (m *FoodData) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodData.DiscardUnknown(m)
}

var xxx_messageInfo_FoodData proto.InternalMessageInfo

func (m *FoodData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FoodData) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *FoodData) GetGenre() *FoodGenre {
	if m != nil {
		return m.Genre
	}
	return nil
}

type FoodCreateQuery struct {
	Data                 *FoodData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FoodCreateQuery) Reset()         { *m = FoodCreateQuery{} }
func (m *FoodCreateQuery) String() string { return proto.CompactTextString(m) }
func (*FoodCreateQuery) ProtoMessage()    {}
func (*FoodCreateQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{3}
}

func (m *FoodCreateQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodCreateQuery.Unmarshal(m, b)
}
func (m *FoodCreateQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodCreateQuery.Marshal(b, m, deterministic)
}
func (m *FoodCreateQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodCreateQuery.Merge(m, src)
}
func (m *FoodCreateQuery) XXX_Size() int {
	return xxx_messageInfo_FoodCreateQuery.Size(m)
}
func (m *FoodCreateQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodCreateQuery.DiscardUnknown(m)
}

var xxx_messageInfo_FoodCreateQuery proto.InternalMessageInfo

func (m *FoodCreateQuery) GetData() *FoodData {
	if m != nil {
		return m.Data
	}
	return nil
}

type FoodCreateResult struct {
	Record               *FoodRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FoodCreateResult) Reset()         { *m = FoodCreateResult{} }
func (m *FoodCreateResult) String() string { return proto.CompactTextString(m) }
func (*FoodCreateResult) ProtoMessage()    {}
func (*FoodCreateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{4}
}

func (m *FoodCreateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodCreateResult.Unmarshal(m, b)
}
func (m *FoodCreateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodCreateResult.Marshal(b, m, deterministic)
}
func (m *FoodCreateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodCreateResult.Merge(m, src)
}
func (m *FoodCreateResult) XXX_Size() int {
	return xxx_messageInfo_FoodCreateResult.Size(m)
}
func (m *FoodCreateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodCreateResult.DiscardUnknown(m)
}

var xxx_messageInfo_FoodCreateResult proto.InternalMessageInfo

func (m *FoodCreateResult) GetRecord() *FoodRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type FoodDeleteQuery struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodDeleteQuery) Reset()         { *m = FoodDeleteQuery{} }
func (m *FoodDeleteQuery) String() string { return proto.CompactTextString(m) }
func (*FoodDeleteQuery) ProtoMessage()    {}
func (*FoodDeleteQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{5}
}

func (m *FoodDeleteQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodDeleteQuery.Unmarshal(m, b)
}
func (m *FoodDeleteQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodDeleteQuery.Marshal(b, m, deterministic)
}
func (m *FoodDeleteQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodDeleteQuery.Merge(m, src)
}
func (m *FoodDeleteQuery) XXX_Size() int {
	return xxx_messageInfo_FoodDeleteQuery.Size(m)
}
func (m *FoodDeleteQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodDeleteQuery.DiscardUnknown(m)
}

var xxx_messageInfo_FoodDeleteQuery proto.InternalMessageInfo

func (m *FoodDeleteQuery) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FoodDeleteResult struct {
	Affected             int64    `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodDeleteResult) Reset()         { *m = FoodDeleteResult{} }
func (m *FoodDeleteResult) String() string { return proto.CompactTextString(m) }
func (*FoodDeleteResult) ProtoMessage()    {}
func (*FoodDeleteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{6}
}

func (m *FoodDeleteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodDeleteResult.Unmarshal(m, b)
}
func (m *FoodDeleteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodDeleteResult.Marshal(b, m, deterministic)
}
func (m *FoodDeleteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodDeleteResult.Merge(m, src)
}
func (m *FoodDeleteResult) XXX_Size() int {
	return xxx_messageInfo_FoodDeleteResult.Size(m)
}
func (m *FoodDeleteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodDeleteResult.DiscardUnknown(m)
}

var xxx_messageInfo_FoodDeleteResult proto.InternalMessageInfo

func (m *FoodDeleteResult) GetAffected() int64 {
	if m != nil {
		return m.Affected
	}
	return 0
}

type FoodGetQuery struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodGetQuery) Reset()         { *m = FoodGetQuery{} }
func (m *FoodGetQuery) String() string { return proto.CompactTextString(m) }
func (*FoodGetQuery) ProtoMessage()    {}
func (*FoodGetQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{7}
}

func (m *FoodGetQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodGetQuery.Unmarshal(m, b)
}
func (m *FoodGetQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodGetQuery.Marshal(b, m, deterministic)
}
func (m *FoodGetQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodGetQuery.Merge(m, src)
}
func (m *FoodGetQuery) XXX_Size() int {
	return xxx_messageInfo_FoodGetQuery.Size(m)
}
func (m *FoodGetQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodGetQuery.DiscardUnknown(m)
}

var xxx_messageInfo_FoodGetQuery proto.InternalMessageInfo

func (m *FoodGetQuery) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FoodGetResult struct {
	Record               *FoodRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FoodGetResult) Reset()         { *m = FoodGetResult{} }
func (m *FoodGetResult) String() string { return proto.CompactTextString(m) }
func (*FoodGetResult) ProtoMessage()    {}
func (*FoodGetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{8}
}

func (m *FoodGetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodGetResult.Unmarshal(m, b)
}
func (m *FoodGetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodGetResult.Marshal(b, m, deterministic)
}
func (m *FoodGetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodGetResult.Merge(m, src)
}
func (m *FoodGetResult) XXX_Size() int {
	return xxx_messageInfo_FoodGetResult.Size(m)
}
func (m *FoodGetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodGetResult.DiscardUnknown(m)
}

var xxx_messageInfo_FoodGetResult proto.InternalMessageInfo

func (m *FoodGetResult) GetRecord() *FoodRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type FoodSearchQuery struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Genre                uint64   `protobuf:"varint,4,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodSearchQuery) Reset()         { *m = FoodSearchQuery{} }
func (m *FoodSearchQuery) String() string { return proto.CompactTextString(m) }
func (*FoodSearchQuery) ProtoMessage()    {}
func (*FoodSearchQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{9}
}

func (m *FoodSearchQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodSearchQuery.Unmarshal(m, b)
}
func (m *FoodSearchQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodSearchQuery.Marshal(b, m, deterministic)
}
func (m *FoodSearchQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodSearchQuery.Merge(m, src)
}
func (m *FoodSearchQuery) XXX_Size() int {
	return xxx_messageInfo_FoodSearchQuery.Size(m)
}
func (m *FoodSearchQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodSearchQuery.DiscardUnknown(m)
}

var xxx_messageInfo_FoodSearchQuery proto.InternalMessageInfo

func (m *FoodSearchQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FoodSearchQuery) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *FoodSearchQuery) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *FoodSearchQuery) GetGenre() uint64 {
	if m != nil {
		return m.Genre
	}
	return 0
}

type FoodSearchResult struct {
	Records              []*FoodRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FoodSearchResult) Reset()         { *m = FoodSearchResult{} }
func (m *FoodSearchResult) String() string { return proto.CompactTextString(m) }
func (*FoodSearchResult) ProtoMessage()    {}
func (*FoodSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{10}
}

func (m *FoodSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodSearchResult.Unmarshal(m, b)
}
func (m *FoodSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodSearchResult.Marshal(b, m, deterministic)
}
func (m *FoodSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodSearchResult.Merge(m, src)
}
func (m *FoodSearchResult) XXX_Size() int {
	return xxx_messageInfo_FoodSearchResult.Size(m)
}
func (m *FoodSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_FoodSearchResult proto.InternalMessageInfo

func (m *FoodSearchResult) GetRecords() []*FoodRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type FoodEmptyQuery struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodEmptyQuery) Reset()         { *m = FoodEmptyQuery{} }
func (m *FoodEmptyQuery) String() string { return proto.CompactTextString(m) }
func (*FoodEmptyQuery) ProtoMessage()    {}
func (*FoodEmptyQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{11}
}

func (m *FoodEmptyQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodEmptyQuery.Unmarshal(m, b)
}
func (m *FoodEmptyQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodEmptyQuery.Marshal(b, m, deterministic)
}
func (m *FoodEmptyQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodEmptyQuery.Merge(m, src)
}
func (m *FoodEmptyQuery) XXX_Size() int {
	return xxx_messageInfo_FoodEmptyQuery.Size(m)
}
func (m *FoodEmptyQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodEmptyQuery.DiscardUnknown(m)
}

var xxx_messageInfo_FoodEmptyQuery proto.InternalMessageInfo

type FoodGetGenresResult struct {
	Genres               []*FoodGenre `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FoodGetGenresResult) Reset()         { *m = FoodGetGenresResult{} }
func (m *FoodGetGenresResult) String() string { return proto.CompactTextString(m) }
func (*FoodGetGenresResult) ProtoMessage()    {}
func (*FoodGetGenresResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52ab5d0a6e96024, []int{12}
}

func (m *FoodGetGenresResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodGetGenresResult.Unmarshal(m, b)
}
func (m *FoodGetGenresResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodGetGenresResult.Marshal(b, m, deterministic)
}
func (m *FoodGetGenresResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodGetGenresResult.Merge(m, src)
}
func (m *FoodGetGenresResult) XXX_Size() int {
	return xxx_messageInfo_FoodGetGenresResult.Size(m)
}
func (m *FoodGetGenresResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodGetGenresResult.DiscardUnknown(m)
}

var xxx_messageInfo_FoodGetGenresResult proto.InternalMessageInfo

func (m *FoodGetGenresResult) GetGenres() []*FoodGenre {
	if m != nil {
		return m.Genres
	}
	return nil
}

func init() {
	proto.RegisterType((*FoodGenre)(nil), "food.FoodGenre")
	proto.RegisterType((*FoodRecord)(nil), "food.FoodRecord")
	proto.RegisterType((*FoodData)(nil), "food.FoodData")
	proto.RegisterType((*FoodCreateQuery)(nil), "food.FoodCreateQuery")
	proto.RegisterType((*FoodCreateResult)(nil), "food.FoodCreateResult")
	proto.RegisterType((*FoodDeleteQuery)(nil), "food.FoodDeleteQuery")
	proto.RegisterType((*FoodDeleteResult)(nil), "food.FoodDeleteResult")
	proto.RegisterType((*FoodGetQuery)(nil), "food.FoodGetQuery")
	proto.RegisterType((*FoodGetResult)(nil), "food.FoodGetResult")
	proto.RegisterType((*FoodSearchQuery)(nil), "food.FoodSearchQuery")
	proto.RegisterType((*FoodSearchResult)(nil), "food.FoodSearchResult")
	proto.RegisterType((*FoodEmptyQuery)(nil), "food.FoodEmptyQuery")
	proto.RegisterType((*FoodGetGenresResult)(nil), "food.FoodGetGenresResult")
}

func init() { proto.RegisterFile("food/messages.proto", fileDescriptor_b52ab5d0a6e96024) }

var fileDescriptor_b52ab5d0a6e96024 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0x26, 0x6d, 0xae, 0xb6, 0xa3, 0xf6, 0xca, 0x9e, 0x0f, 0xe5, 0x10, 0xa9, 0x0b, 0x62, 0x11,
	0x2e, 0x01, 0x45, 0xe4, 0x40, 0x0e, 0xd1, 0x53, 0x9f, 0x5d, 0xdf, 0xf4, 0x69, 0x9b, 0x4c, 0xd3,
	0x40, 0x92, 0x0d, 0xbb, 0x9b, 0x93, 0xfe, 0x7b, 0xd9, 0x9d, 0x4d, 0xf2, 0xd0, 0x22, 0xf8, 0x96,
	0x99, 0x6f, 0xe6, 0xfb, 0xbe, 0x99, 0xd9, 0xc0, 0xd5, 0x5e, 0xa9, 0x3c, 0xad, 0xd1, 0x18, 0x59,
	0xa0, 0x49, 0x5a, 0xad, 0xac, 0x62, 0xb1, 0x4b, 0xf2, 0x14, 0x16, 0xdf, 0x94, 0xca, 0xbf, 0x63,
	0xa3, 0x91, 0x2d, 0x61, 0x52, 0xe6, 0xeb, 0x68, 0x13, 0x6d, 0x63, 0x31, 0x29, 0x73, 0xc6, 0x20,
	0x6e, 0x64, 0x8d, 0xeb, 0xc9, 0x26, 0xda, 0x2e, 0x84, 0xff, 0xe6, 0x9f, 0x00, 0x5c, 0x83, 0xc0,
	0x4c, 0xe9, 0xfc, 0xa4, 0x83, 0x43, 0x9c, 0x4b, 0x2b, 0x7d, 0xc7, 0xe3, 0xb7, 0xcb, 0xc4, 0x69,
	0x24, 0xae, 0xfe, 0x5e, 0x5a, 0x29, 0x3c, 0xc6, 0x7f, 0xc3, 0xbc, 0xcf, 0x0c, 0x0a, 0xd1, 0xa8,
	0xc0, 0x9e, 0xc1, 0x45, 0xab, 0xcb, 0x8c, 0x64, 0x63, 0x41, 0x01, 0x7b, 0x05, 0x17, 0x85, 0x33,
	0xb9, 0x9e, 0x7a, 0xea, 0xcb, 0x91, 0xda, 0x7b, 0x17, 0x84, 0xf2, 0xf7, 0x70, 0xe9, 0x72, 0x5f,
	0x34, 0x4a, 0x8b, 0x3f, 0x3a, 0xd4, 0xc7, 0xc1, 0x53, 0xf4, 0x0f, 0x4f, 0x1f, 0x61, 0x35, 0xb6,
	0x09, 0x34, 0x5d, 0x65, 0xd9, 0x16, 0x66, 0xda, 0x4f, 0x19, 0x3a, 0x57, 0x63, 0x27, 0x4d, 0x2f,
	0x02, 0xce, 0x5f, 0x92, 0xe8, 0x3d, 0x56, 0xd8, 0x8b, 0x8e, 0x8b, 0x99, 0xba, 0xc5, 0xf0, 0x84,
	0x04, 0xa8, 0x24, 0x08, 0x5c, 0xc3, 0x5c, 0xee, 0xf7, 0x98, 0x59, 0xec, 0x2b, 0x87, 0x98, 0xbf,
	0x80, 0x27, 0x34, 0x9b, 0x3d, 0xcf, 0x77, 0x0b, 0x4f, 0x03, 0xfe, 0xdf, 0x6e, 0x3b, 0x72, 0xfb,
	0x13, 0xa5, 0xce, 0x0e, 0xc4, 0x7e, 0xee, 0x0c, 0xd7, 0x30, 0xaf, 0xa4, 0x2d, 0x6d, 0x97, 0xd3,
	0x25, 0x22, 0x31, 0xc4, 0xec, 0x39, 0x2c, 0x2a, 0xd5, 0x14, 0x04, 0x4e, 0x3d, 0x38, 0x26, 0xdc,
	0x01, 0xe9, 0x54, 0x31, 0x1d, 0x90, 0x2e, 0x73, 0x47, 0x1b, 0x20, 0xd9, 0x60, 0xfa, 0x0d, 0x3c,
	0x22, 0x53, 0x66, 0x1d, 0x6d, 0xa6, 0x67, 0x5d, 0xf7, 0x05, 0x7c, 0x05, 0x4b, 0x97, 0xfe, 0x5a,
	0xb7, 0xf6, 0xe8, 0x5d, 0xf3, 0x3b, 0xb8, 0x0a, 0x3b, 0xf0, 0x4f, 0xc0, 0x04, 0xd2, 0xd7, 0x30,
	0xf3, 0x8a, 0x3d, 0xe7, 0xc9, 0x53, 0x09, 0xf0, 0xe7, 0xdb, 0x5f, 0x1f, 0x8a, 0xd2, 0x1e, 0xba,
	0x5d, 0x92, 0xa9, 0x3a, 0x6d, 0xb5, 0xc2, 0x6a, 0x67, 0x9b, 0xd4, 0x64, 0x07, 0xa5, 0xaa, 0x1b,
	0x7c, 0xc0, 0x9b, 0x46, 0x3e, 0x94, 0x69, 0x21, 0x2d, 0xfe, 0x91, 0xc7, 0xd4, 0xff, 0x36, 0x26,
	0x75, 0x64, 0xbb, 0x99, 0x0f, 0xde, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x18, 0xea, 0x0d,
	0x5a, 0x03, 0x00, 0x00,
}
