// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shop/messages.proto

package shop

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShopGenre struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopGenre) Reset()         { *m = ShopGenre{} }
func (m *ShopGenre) String() string { return proto.CompactTextString(m) }
func (*ShopGenre) ProtoMessage()    {}
func (*ShopGenre) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{0}
}

func (m *ShopGenre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopGenre.Unmarshal(m, b)
}
func (m *ShopGenre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopGenre.Marshal(b, m, deterministic)
}
func (m *ShopGenre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopGenre.Merge(m, src)
}
func (m *ShopGenre) XXX_Size() int {
	return xxx_messageInfo_ShopGenre.Size(m)
}
func (m *ShopGenre) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopGenre.DiscardUnknown(m)
}

var xxx_messageInfo_ShopGenre proto.InternalMessageInfo

func (m *ShopGenre) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShopGenre) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ShopRecord struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *ShopData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShopRecord) Reset()         { *m = ShopRecord{} }
func (m *ShopRecord) String() string { return proto.CompactTextString(m) }
func (*ShopRecord) ProtoMessage()    {}
func (*ShopRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{1}
}

func (m *ShopRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopRecord.Unmarshal(m, b)
}
func (m *ShopRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopRecord.Marshal(b, m, deterministic)
}
func (m *ShopRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopRecord.Merge(m, src)
}
func (m *ShopRecord) XXX_Size() int {
	return xxx_messageInfo_ShopRecord.Size(m)
}
func (m *ShopRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ShopRecord proto.InternalMessageInfo

func (m *ShopRecord) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShopRecord) GetData() *ShopData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShopData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GenreId              uint64   `protobuf:"varint,3,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	Longitude            float64  `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Open                 uint64   `protobuf:"varint,7,opt,name=open,proto3" json:"open,omitempty"`
	Close                uint64   `protobuf:"varint,8,opt,name=close,proto3" json:"close,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopData) Reset()         { *m = ShopData{} }
func (m *ShopData) String() string { return proto.CompactTextString(m) }
func (*ShopData) ProtoMessage()    {}
func (*ShopData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{2}
}

func (m *ShopData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopData.Unmarshal(m, b)
}
func (m *ShopData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopData.Marshal(b, m, deterministic)
}
func (m *ShopData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopData.Merge(m, src)
}
func (m *ShopData) XXX_Size() int {
	return xxx_messageInfo_ShopData.Size(m)
}
func (m *ShopData) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopData.DiscardUnknown(m)
}

var xxx_messageInfo_ShopData proto.InternalMessageInfo

func (m *ShopData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShopData) GetGenreId() uint64 {
	if m != nil {
		return m.GenreId
	}
	return 0
}

func (m *ShopData) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *ShopData) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *ShopData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ShopData) GetOpen() uint64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *ShopData) GetClose() uint64 {
	if m != nil {
		return m.Close
	}
	return 0
}

type ShopCreateQuery struct {
	Data                 *ShopData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShopCreateQuery) Reset()         { *m = ShopCreateQuery{} }
func (m *ShopCreateQuery) String() string { return proto.CompactTextString(m) }
func (*ShopCreateQuery) ProtoMessage()    {}
func (*ShopCreateQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{3}
}

func (m *ShopCreateQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopCreateQuery.Unmarshal(m, b)
}
func (m *ShopCreateQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopCreateQuery.Marshal(b, m, deterministic)
}
func (m *ShopCreateQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopCreateQuery.Merge(m, src)
}
func (m *ShopCreateQuery) XXX_Size() int {
	return xxx_messageInfo_ShopCreateQuery.Size(m)
}
func (m *ShopCreateQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopCreateQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ShopCreateQuery proto.InternalMessageInfo

func (m *ShopCreateQuery) GetData() *ShopData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShopCreateResult struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopCreateResult) Reset()         { *m = ShopCreateResult{} }
func (m *ShopCreateResult) String() string { return proto.CompactTextString(m) }
func (*ShopCreateResult) ProtoMessage()    {}
func (*ShopCreateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{4}
}

func (m *ShopCreateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopCreateResult.Unmarshal(m, b)
}
func (m *ShopCreateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopCreateResult.Marshal(b, m, deterministic)
}
func (m *ShopCreateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopCreateResult.Merge(m, src)
}
func (m *ShopCreateResult) XXX_Size() int {
	return xxx_messageInfo_ShopCreateResult.Size(m)
}
func (m *ShopCreateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopCreateResult.DiscardUnknown(m)
}

var xxx_messageInfo_ShopCreateResult proto.InternalMessageInfo

func (m *ShopCreateResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ShopDeleteQuery struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopDeleteQuery) Reset()         { *m = ShopDeleteQuery{} }
func (m *ShopDeleteQuery) String() string { return proto.CompactTextString(m) }
func (*ShopDeleteQuery) ProtoMessage()    {}
func (*ShopDeleteQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{5}
}

func (m *ShopDeleteQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopDeleteQuery.Unmarshal(m, b)
}
func (m *ShopDeleteQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopDeleteQuery.Marshal(b, m, deterministic)
}
func (m *ShopDeleteQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopDeleteQuery.Merge(m, src)
}
func (m *ShopDeleteQuery) XXX_Size() int {
	return xxx_messageInfo_ShopDeleteQuery.Size(m)
}
func (m *ShopDeleteQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopDeleteQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ShopDeleteQuery proto.InternalMessageInfo

func (m *ShopDeleteQuery) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ShopDeleteResult struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopDeleteResult) Reset()         { *m = ShopDeleteResult{} }
func (m *ShopDeleteResult) String() string { return proto.CompactTextString(m) }
func (*ShopDeleteResult) ProtoMessage()    {}
func (*ShopDeleteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{6}
}

func (m *ShopDeleteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopDeleteResult.Unmarshal(m, b)
}
func (m *ShopDeleteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopDeleteResult.Marshal(b, m, deterministic)
}
func (m *ShopDeleteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopDeleteResult.Merge(m, src)
}
func (m *ShopDeleteResult) XXX_Size() int {
	return xxx_messageInfo_ShopDeleteResult.Size(m)
}
func (m *ShopDeleteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopDeleteResult.DiscardUnknown(m)
}

var xxx_messageInfo_ShopDeleteResult proto.InternalMessageInfo

func (m *ShopDeleteResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ShopGetQuery struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopGetQuery) Reset()         { *m = ShopGetQuery{} }
func (m *ShopGetQuery) String() string { return proto.CompactTextString(m) }
func (*ShopGetQuery) ProtoMessage()    {}
func (*ShopGetQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{7}
}

func (m *ShopGetQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopGetQuery.Unmarshal(m, b)
}
func (m *ShopGetQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopGetQuery.Marshal(b, m, deterministic)
}
func (m *ShopGetQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopGetQuery.Merge(m, src)
}
func (m *ShopGetQuery) XXX_Size() int {
	return xxx_messageInfo_ShopGetQuery.Size(m)
}
func (m *ShopGetQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopGetQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ShopGetQuery proto.InternalMessageInfo

func (m *ShopGetQuery) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ShopGetResult struct {
	Record               *ShopRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ShopGetResult) Reset()         { *m = ShopGetResult{} }
func (m *ShopGetResult) String() string { return proto.CompactTextString(m) }
func (*ShopGetResult) ProtoMessage()    {}
func (*ShopGetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{8}
}

func (m *ShopGetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopGetResult.Unmarshal(m, b)
}
func (m *ShopGetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopGetResult.Marshal(b, m, deterministic)
}
func (m *ShopGetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopGetResult.Merge(m, src)
}
func (m *ShopGetResult) XXX_Size() int {
	return xxx_messageInfo_ShopGetResult.Size(m)
}
func (m *ShopGetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopGetResult.DiscardUnknown(m)
}

var xxx_messageInfo_ShopGetResult proto.InternalMessageInfo

func (m *ShopGetResult) GetRecord() *ShopRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type ShopSearchQuery struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GenreId              uint64   `protobuf:"varint,4,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopSearchQuery) Reset()         { *m = ShopSearchQuery{} }
func (m *ShopSearchQuery) String() string { return proto.CompactTextString(m) }
func (*ShopSearchQuery) ProtoMessage()    {}
func (*ShopSearchQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{9}
}

func (m *ShopSearchQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopSearchQuery.Unmarshal(m, b)
}
func (m *ShopSearchQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopSearchQuery.Marshal(b, m, deterministic)
}
func (m *ShopSearchQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopSearchQuery.Merge(m, src)
}
func (m *ShopSearchQuery) XXX_Size() int {
	return xxx_messageInfo_ShopSearchQuery.Size(m)
}
func (m *ShopSearchQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopSearchQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ShopSearchQuery proto.InternalMessageInfo

func (m *ShopSearchQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShopSearchQuery) GetGenreId() uint64 {
	if m != nil {
		return m.GenreId
	}
	return 0
}

type ShopSearchResult struct {
	Records              []*ShopRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ShopSearchResult) Reset()         { *m = ShopSearchResult{} }
func (m *ShopSearchResult) String() string { return proto.CompactTextString(m) }
func (*ShopSearchResult) ProtoMessage()    {}
func (*ShopSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{10}
}

func (m *ShopSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopSearchResult.Unmarshal(m, b)
}
func (m *ShopSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopSearchResult.Marshal(b, m, deterministic)
}
func (m *ShopSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopSearchResult.Merge(m, src)
}
func (m *ShopSearchResult) XXX_Size() int {
	return xxx_messageInfo_ShopSearchResult.Size(m)
}
func (m *ShopSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_ShopSearchResult proto.InternalMessageInfo

func (m *ShopSearchResult) GetRecords() []*ShopRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type ShopEmptyQuery struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopEmptyQuery) Reset()         { *m = ShopEmptyQuery{} }
func (m *ShopEmptyQuery) String() string { return proto.CompactTextString(m) }
func (*ShopEmptyQuery) ProtoMessage()    {}
func (*ShopEmptyQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{11}
}

func (m *ShopEmptyQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopEmptyQuery.Unmarshal(m, b)
}
func (m *ShopEmptyQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopEmptyQuery.Marshal(b, m, deterministic)
}
func (m *ShopEmptyQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopEmptyQuery.Merge(m, src)
}
func (m *ShopEmptyQuery) XXX_Size() int {
	return xxx_messageInfo_ShopEmptyQuery.Size(m)
}
func (m *ShopEmptyQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopEmptyQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ShopEmptyQuery proto.InternalMessageInfo

type ShopGetGenresResult struct {
	Genres               []*ShopGenre `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ShopGetGenresResult) Reset()         { *m = ShopGetGenresResult{} }
func (m *ShopGetGenresResult) String() string { return proto.CompactTextString(m) }
func (*ShopGetGenresResult) ProtoMessage()    {}
func (*ShopGetGenresResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{12}
}

func (m *ShopGetGenresResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopGetGenresResult.Unmarshal(m, b)
}
func (m *ShopGetGenresResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopGetGenresResult.Marshal(b, m, deterministic)
}
func (m *ShopGetGenresResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopGetGenresResult.Merge(m, src)
}
func (m *ShopGetGenresResult) XXX_Size() int {
	return xxx_messageInfo_ShopGetGenresResult.Size(m)
}
func (m *ShopGetGenresResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopGetGenresResult.DiscardUnknown(m)
}

var xxx_messageInfo_ShopGetGenresResult proto.InternalMessageInfo

func (m *ShopGetGenresResult) GetGenres() []*ShopGenre {
	if m != nil {
		return m.Genres
	}
	return nil
}

func init() {
	proto.RegisterType((*ShopGenre)(nil), "shop.ShopGenre")
	proto.RegisterType((*ShopRecord)(nil), "shop.ShopRecord")
	proto.RegisterType((*ShopData)(nil), "shop.ShopData")
	proto.RegisterType((*ShopCreateQuery)(nil), "shop.ShopCreateQuery")
	proto.RegisterType((*ShopCreateResult)(nil), "shop.ShopCreateResult")
	proto.RegisterType((*ShopDeleteQuery)(nil), "shop.ShopDeleteQuery")
	proto.RegisterType((*ShopDeleteResult)(nil), "shop.ShopDeleteResult")
	proto.RegisterType((*ShopGetQuery)(nil), "shop.ShopGetQuery")
	proto.RegisterType((*ShopGetResult)(nil), "shop.ShopGetResult")
	proto.RegisterType((*ShopSearchQuery)(nil), "shop.ShopSearchQuery")
	proto.RegisterType((*ShopSearchResult)(nil), "shop.ShopSearchResult")
	proto.RegisterType((*ShopEmptyQuery)(nil), "shop.ShopEmptyQuery")
	proto.RegisterType((*ShopGetGenresResult)(nil), "shop.ShopGetGenresResult")
}

func init() { proto.RegisterFile("shop/messages.proto", fileDescriptor_fa9375cd29e3697d) }

var fileDescriptor_fa9375cd29e3697d = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4f, 0x8b, 0xd3, 0x40,
	0x14, 0x27, 0x6d, 0xb6, 0x4d, 0x9f, 0xda, 0x2d, 0xb3, 0x1e, 0xa2, 0x88, 0xd4, 0xb9, 0x58, 0xc4,
	0x6d, 0x40, 0x11, 0xd9, 0xcb, 0xb2, 0xe8, 0x8a, 0x78, 0x74, 0xf6, 0xe6, 0x45, 0xa6, 0x99, 0x47,
	0x12, 0x48, 0x33, 0x61, 0x66, 0xb2, 0xd2, 0x4f, 0xe6, 0xd7, 0x93, 0x79, 0x93, 0x34, 0x2a, 0xcb,
	0xee, 0x6d, 0xde, 0xbf, 0xdf, 0x1f, 0x7e, 0x09, 0x9c, 0xd9, 0x52, 0xb7, 0xd9, 0x1e, 0xad, 0x95,
	0x05, 0xda, 0x6d, 0x6b, 0xb4, 0xd3, 0x2c, 0xf6, 0x4d, 0x9e, 0xc1, 0xe2, 0xa6, 0xd4, 0xed, 0x57,
	0x6c, 0x0c, 0xb2, 0x25, 0x4c, 0x2a, 0x95, 0x46, 0xeb, 0x68, 0x13, 0x8b, 0x49, 0xa5, 0x18, 0x83,
	0xb8, 0x91, 0x7b, 0x4c, 0x27, 0xeb, 0x68, 0xb3, 0x10, 0xf4, 0xe6, 0x57, 0x00, 0xfe, 0x40, 0x60,
	0xae, 0x8d, 0xfa, 0xeb, 0x62, 0x4a, 0x17, 0x1c, 0x62, 0x25, 0x9d, 0xa4, 0x8b, 0x47, 0xef, 0x96,
	0x5b, 0xcf, 0xb1, 0xf5, 0xfb, 0xd7, 0xd2, 0x49, 0x41, 0x33, 0xfe, 0x3b, 0x82, 0x64, 0x68, 0x1d,
	0x29, 0xa2, 0x91, 0x82, 0x3d, 0x83, 0xa4, 0xf0, 0x7a, 0x7e, 0x56, 0x2a, 0x9d, 0x92, 0x98, 0x39,
	0xd5, 0xdf, 0x14, 0x7b, 0x01, 0x8b, 0x5a, 0x37, 0x45, 0xe5, 0x3a, 0x85, 0x69, 0xbc, 0x8e, 0x36,
	0x91, 0x18, 0x1b, 0xec, 0x39, 0x24, 0xb5, 0x74, 0x61, 0x78, 0x42, 0xc3, 0x63, 0xcd, 0x52, 0x98,
	0x4b, 0xa5, 0x0c, 0x5a, 0x9b, 0xce, 0x88, 0x6b, 0x28, 0xbd, 0x04, 0xdd, 0x62, 0x93, 0xce, 0x89,
	0x8a, 0xde, 0xec, 0x29, 0x9c, 0xe4, 0xb5, 0xb6, 0x98, 0x26, 0xd4, 0x0c, 0x05, 0xff, 0x00, 0xa7,
	0x5e, 0xf8, 0x67, 0x83, 0xd2, 0xe1, 0xf7, 0x0e, 0xcd, 0xe1, 0x68, 0x38, 0xba, 0xc7, 0xf0, 0x5b,
	0x58, 0x8d, 0x67, 0x02, 0x6d, 0x57, 0x3b, 0x2f, 0xc7, 0x76, 0x79, 0xee, 0xe5, 0xf8, 0xd3, 0x44,
	0x0c, 0x25, 0x7f, 0x15, 0x48, 0xae, 0xb1, 0xc6, 0x81, 0xe4, 0xbf, 0x5c, 0x06, 0xc0, 0xb0, 0xf2,
	0x20, 0xe0, 0x4b, 0x78, 0x1c, 0x22, 0x76, 0x77, 0xa3, 0x5d, 0xc0, 0x93, 0x7e, 0xde, 0x43, 0x6d,
	0x60, 0x66, 0x28, 0xde, 0xde, 0xd5, 0x6a, 0x74, 0x15, 0x62, 0x17, 0xfd, 0x9c, 0x5f, 0x05, 0xad,
	0x37, 0x28, 0x4d, 0x5e, 0x06, 0xf4, 0x87, 0x02, 0x8d, 0xff, 0x09, 0x94, 0x5f, 0x06, 0x2b, 0x01,
	0xa1, 0xe7, 0x7f, 0x03, 0xf3, 0x80, 0xef, 0xad, 0x4c, 0xef, 0x14, 0x30, 0x2c, 0xf0, 0x15, 0x2c,
	0x7d, 0xfb, 0xcb, 0xbe, 0x75, 0x07, 0x12, 0xc0, 0x2f, 0xe1, 0xac, 0xb7, 0x43, 0x1f, 0xb5, 0xed,
	0x41, 0x5f, 0xc3, 0x8c, 0x38, 0x07, 0xcc, 0xd3, 0x11, 0x93, 0xf6, 0x44, 0x3f, 0xfe, 0x74, 0xf1,
	0xe3, 0x63, 0x51, 0xb9, 0xb2, 0xdb, 0x6d, 0x73, 0xbd, 0xcf, 0x5a, 0xa3, 0xb1, 0xde, 0xb9, 0x26,
	0xb3, 0x79, 0xa9, 0x75, 0x7d, 0x8e, 0xb7, 0x78, 0xde, 0xc8, 0xdb, 0x2a, 0x2b, 0xa4, 0xc3, 0x5f,
	0xf2, 0x90, 0xd1, 0xcf, 0x64, 0x33, 0x0f, 0xb6, 0x9b, 0x51, 0xf1, 0xfe, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x41, 0x72, 0x97, 0x57, 0x70, 0x03, 0x00, 0x00,
}
