// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shop/messages.proto

package shop

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShopGenre int32

const (
	ShopGenre_Invalid ShopGenre = 0
)

var ShopGenre_name = map[int32]string{
	0: "Invalid",
}

var ShopGenre_value = map[string]int32{
	"Invalid": 0,
}

func (x ShopGenre) String() string {
	return proto.EnumName(ShopGenre_name, int32(x))
}

func (ShopGenre) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{0}
}

type ShopRecord struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *ShopData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShopRecord) Reset()         { *m = ShopRecord{} }
func (m *ShopRecord) String() string { return proto.CompactTextString(m) }
func (*ShopRecord) ProtoMessage()    {}
func (*ShopRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{0}
}

func (m *ShopRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopRecord.Unmarshal(m, b)
}
func (m *ShopRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopRecord.Marshal(b, m, deterministic)
}
func (m *ShopRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopRecord.Merge(m, src)
}
func (m *ShopRecord) XXX_Size() int {
	return xxx_messageInfo_ShopRecord.Size(m)
}
func (m *ShopRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ShopRecord proto.InternalMessageInfo

func (m *ShopRecord) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShopRecord) GetData() *ShopData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShopData struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                uint64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Genre                ShopGenre `protobuf:"varint,3,opt,name=genre,proto3,enum=shop.ShopGenre" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShopData) Reset()         { *m = ShopData{} }
func (m *ShopData) String() string { return proto.CompactTextString(m) }
func (*ShopData) ProtoMessage()    {}
func (*ShopData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{1}
}

func (m *ShopData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopData.Unmarshal(m, b)
}
func (m *ShopData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopData.Marshal(b, m, deterministic)
}
func (m *ShopData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopData.Merge(m, src)
}
func (m *ShopData) XXX_Size() int {
	return xxx_messageInfo_ShopData.Size(m)
}
func (m *ShopData) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopData.DiscardUnknown(m)
}

var xxx_messageInfo_ShopData proto.InternalMessageInfo

func (m *ShopData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShopData) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ShopData) GetGenre() ShopGenre {
	if m != nil {
		return m.Genre
	}
	return ShopGenre_Invalid
}

type ShopCreateQuery struct {
	Data                 *ShopData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShopCreateQuery) Reset()         { *m = ShopCreateQuery{} }
func (m *ShopCreateQuery) String() string { return proto.CompactTextString(m) }
func (*ShopCreateQuery) ProtoMessage()    {}
func (*ShopCreateQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{2}
}

func (m *ShopCreateQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopCreateQuery.Unmarshal(m, b)
}
func (m *ShopCreateQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopCreateQuery.Marshal(b, m, deterministic)
}
func (m *ShopCreateQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopCreateQuery.Merge(m, src)
}
func (m *ShopCreateQuery) XXX_Size() int {
	return xxx_messageInfo_ShopCreateQuery.Size(m)
}
func (m *ShopCreateQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopCreateQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ShopCreateQuery proto.InternalMessageInfo

func (m *ShopCreateQuery) GetData() *ShopData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShopCreateResult struct {
	Record               *ShopRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ShopCreateResult) Reset()         { *m = ShopCreateResult{} }
func (m *ShopCreateResult) String() string { return proto.CompactTextString(m) }
func (*ShopCreateResult) ProtoMessage()    {}
func (*ShopCreateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{3}
}

func (m *ShopCreateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopCreateResult.Unmarshal(m, b)
}
func (m *ShopCreateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopCreateResult.Marshal(b, m, deterministic)
}
func (m *ShopCreateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopCreateResult.Merge(m, src)
}
func (m *ShopCreateResult) XXX_Size() int {
	return xxx_messageInfo_ShopCreateResult.Size(m)
}
func (m *ShopCreateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopCreateResult.DiscardUnknown(m)
}

var xxx_messageInfo_ShopCreateResult proto.InternalMessageInfo

func (m *ShopCreateResult) GetRecord() *ShopRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type ShopDeleteQuery struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopDeleteQuery) Reset()         { *m = ShopDeleteQuery{} }
func (m *ShopDeleteQuery) String() string { return proto.CompactTextString(m) }
func (*ShopDeleteQuery) ProtoMessage()    {}
func (*ShopDeleteQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{4}
}

func (m *ShopDeleteQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopDeleteQuery.Unmarshal(m, b)
}
func (m *ShopDeleteQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopDeleteQuery.Marshal(b, m, deterministic)
}
func (m *ShopDeleteQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopDeleteQuery.Merge(m, src)
}
func (m *ShopDeleteQuery) XXX_Size() int {
	return xxx_messageInfo_ShopDeleteQuery.Size(m)
}
func (m *ShopDeleteQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopDeleteQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ShopDeleteQuery proto.InternalMessageInfo

func (m *ShopDeleteQuery) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ShopDeleteResult struct {
	Affected             int64    `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopDeleteResult) Reset()         { *m = ShopDeleteResult{} }
func (m *ShopDeleteResult) String() string { return proto.CompactTextString(m) }
func (*ShopDeleteResult) ProtoMessage()    {}
func (*ShopDeleteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{5}
}

func (m *ShopDeleteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopDeleteResult.Unmarshal(m, b)
}
func (m *ShopDeleteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopDeleteResult.Marshal(b, m, deterministic)
}
func (m *ShopDeleteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopDeleteResult.Merge(m, src)
}
func (m *ShopDeleteResult) XXX_Size() int {
	return xxx_messageInfo_ShopDeleteResult.Size(m)
}
func (m *ShopDeleteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopDeleteResult.DiscardUnknown(m)
}

var xxx_messageInfo_ShopDeleteResult proto.InternalMessageInfo

func (m *ShopDeleteResult) GetAffected() int64 {
	if m != nil {
		return m.Affected
	}
	return 0
}

type ShopGetQuery struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopGetQuery) Reset()         { *m = ShopGetQuery{} }
func (m *ShopGetQuery) String() string { return proto.CompactTextString(m) }
func (*ShopGetQuery) ProtoMessage()    {}
func (*ShopGetQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{6}
}

func (m *ShopGetQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopGetQuery.Unmarshal(m, b)
}
func (m *ShopGetQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopGetQuery.Marshal(b, m, deterministic)
}
func (m *ShopGetQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopGetQuery.Merge(m, src)
}
func (m *ShopGetQuery) XXX_Size() int {
	return xxx_messageInfo_ShopGetQuery.Size(m)
}
func (m *ShopGetQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopGetQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ShopGetQuery proto.InternalMessageInfo

func (m *ShopGetQuery) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ShopGetResult struct {
	Record               *ShopRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ShopGetResult) Reset()         { *m = ShopGetResult{} }
func (m *ShopGetResult) String() string { return proto.CompactTextString(m) }
func (*ShopGetResult) ProtoMessage()    {}
func (*ShopGetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{7}
}

func (m *ShopGetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopGetResult.Unmarshal(m, b)
}
func (m *ShopGetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopGetResult.Marshal(b, m, deterministic)
}
func (m *ShopGetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopGetResult.Merge(m, src)
}
func (m *ShopGetResult) XXX_Size() int {
	return xxx_messageInfo_ShopGetResult.Size(m)
}
func (m *ShopGetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopGetResult.DiscardUnknown(m)
}

var xxx_messageInfo_ShopGetResult proto.InternalMessageInfo

func (m *ShopGetResult) GetRecord() *ShopRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type ShopSearchQuery struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude             float64   `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64   `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Genre                ShopGenre `protobuf:"varint,4,opt,name=genre,proto3,enum=shop.ShopGenre" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShopSearchQuery) Reset()         { *m = ShopSearchQuery{} }
func (m *ShopSearchQuery) String() string { return proto.CompactTextString(m) }
func (*ShopSearchQuery) ProtoMessage()    {}
func (*ShopSearchQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{8}
}

func (m *ShopSearchQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopSearchQuery.Unmarshal(m, b)
}
func (m *ShopSearchQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopSearchQuery.Marshal(b, m, deterministic)
}
func (m *ShopSearchQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopSearchQuery.Merge(m, src)
}
func (m *ShopSearchQuery) XXX_Size() int {
	return xxx_messageInfo_ShopSearchQuery.Size(m)
}
func (m *ShopSearchQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopSearchQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ShopSearchQuery proto.InternalMessageInfo

func (m *ShopSearchQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShopSearchQuery) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *ShopSearchQuery) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *ShopSearchQuery) GetGenre() ShopGenre {
	if m != nil {
		return m.Genre
	}
	return ShopGenre_Invalid
}

type ShopSearchResult struct {
	Records              []*ShopRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ShopSearchResult) Reset()         { *m = ShopSearchResult{} }
func (m *ShopSearchResult) String() string { return proto.CompactTextString(m) }
func (*ShopSearchResult) ProtoMessage()    {}
func (*ShopSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9375cd29e3697d, []int{9}
}

func (m *ShopSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopSearchResult.Unmarshal(m, b)
}
func (m *ShopSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopSearchResult.Marshal(b, m, deterministic)
}
func (m *ShopSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopSearchResult.Merge(m, src)
}
func (m *ShopSearchResult) XXX_Size() int {
	return xxx_messageInfo_ShopSearchResult.Size(m)
}
func (m *ShopSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_ShopSearchResult proto.InternalMessageInfo

func (m *ShopSearchResult) GetRecords() []*ShopRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterEnum("shop.ShopGenre", ShopGenre_name, ShopGenre_value)
	proto.RegisterType((*ShopRecord)(nil), "shop.ShopRecord")
	proto.RegisterType((*ShopData)(nil), "shop.ShopData")
	proto.RegisterType((*ShopCreateQuery)(nil), "shop.ShopCreateQuery")
	proto.RegisterType((*ShopCreateResult)(nil), "shop.ShopCreateResult")
	proto.RegisterType((*ShopDeleteQuery)(nil), "shop.ShopDeleteQuery")
	proto.RegisterType((*ShopDeleteResult)(nil), "shop.ShopDeleteResult")
	proto.RegisterType((*ShopGetQuery)(nil), "shop.ShopGetQuery")
	proto.RegisterType((*ShopGetResult)(nil), "shop.ShopGetResult")
	proto.RegisterType((*ShopSearchQuery)(nil), "shop.ShopSearchQuery")
	proto.RegisterType((*ShopSearchResult)(nil), "shop.ShopSearchResult")
}

func init() { proto.RegisterFile("shop/messages.proto", fileDescriptor_fa9375cd29e3697d) }

var fileDescriptor_fa9375cd29e3697d = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x5f, 0x8b, 0xd3, 0x40,
	0x10, 0x77, 0x9b, 0xdc, 0x5d, 0x3b, 0xa7, 0xbd, 0xb2, 0xfa, 0x10, 0x0e, 0x91, 0x18, 0x10, 0x42,
	0xa1, 0x09, 0x54, 0x44, 0x0a, 0x22, 0xa2, 0x05, 0xf1, 0xd1, 0xed, 0x9b, 0x3e, 0x6d, 0x93, 0x69,
	0x12, 0x48, 0xb3, 0x61, 0x77, 0x53, 0xe9, 0x17, 0xf0, 0x73, 0x4b, 0x76, 0xf3, 0x07, 0xa4, 0x14,
	0xee, 0x2d, 0x33, 0xbf, 0x99, 0xdf, 0x9f, 0x9d, 0xc0, 0x4b, 0x95, 0x8b, 0x3a, 0x3e, 0xa2, 0x52,
	0x3c, 0x43, 0x15, 0xd5, 0x52, 0x68, 0x41, 0xdd, 0xb6, 0x19, 0x7c, 0x01, 0xd8, 0xe5, 0xa2, 0x66,
	0x98, 0x08, 0x99, 0xd2, 0x39, 0x4c, 0x8a, 0xd4, 0x23, 0x3e, 0x09, 0x1d, 0x36, 0x29, 0x52, 0x1a,
	0x80, 0x9b, 0x72, 0xcd, 0xbd, 0x89, 0x4f, 0xc2, 0xfb, 0xf5, 0x3c, 0x6a, 0x57, 0xa2, 0x76, 0x7e,
	0xcb, 0x35, 0x67, 0x06, 0x0b, 0x7e, 0xc3, 0xb4, 0xef, 0x50, 0x0a, 0x6e, 0xc5, 0x8f, 0x68, 0x18,
	0x66, 0xcc, 0x7c, 0xd3, 0x57, 0x70, 0x53, 0xcb, 0x22, 0x41, 0x43, 0xe2, 0x32, 0x5b, 0xd0, 0x77,
	0x70, 0x93, 0x61, 0x25, 0xd1, 0x73, 0x7c, 0x12, 0xce, 0xd7, 0x0f, 0x23, 0xf5, 0xf7, 0xb6, 0xcd,
	0x2c, 0x1a, 0x7c, 0x80, 0x87, 0xb6, 0xf7, 0x4d, 0x22, 0xd7, 0xf8, 0xb3, 0x41, 0x79, 0x1e, 0x3c,
	0x91, 0x2b, 0x9e, 0x3e, 0xc1, 0x62, 0x5c, 0x63, 0xa8, 0x9a, 0x52, 0xd3, 0x10, 0x6e, 0xa5, 0x49,
	0xd9, 0x6d, 0x2e, 0xc6, 0x4d, 0x9b, 0x9e, 0x75, 0x78, 0xf0, 0xd6, 0x8a, 0x6e, 0xb1, 0xc4, 0x5e,
	0xf4, 0xbf, 0x87, 0x09, 0x22, 0x2b, 0x60, 0x47, 0x3a, 0x81, 0x47, 0x98, 0xf2, 0xc3, 0x01, 0x13,
	0x8d, 0xfd, 0xe4, 0x50, 0x07, 0x6f, 0xe0, 0xb9, 0xcd, 0xa6, 0x2f, 0xf3, 0x6d, 0xe0, 0x45, 0x87,
	0x3f, 0xd9, 0xed, 0x5f, 0x62, 0xed, 0xee, 0x90, 0xcb, 0x24, 0xb7, 0xf4, 0x97, 0xee, 0xf0, 0x08,
	0xd3, 0x92, 0xeb, 0x42, 0x37, 0xa9, 0x3d, 0x05, 0x61, 0x43, 0x4d, 0x5f, 0xc3, 0xac, 0x14, 0x55,
	0x66, 0x41, 0xc7, 0x80, 0x63, 0x63, 0xbc, 0x95, 0x7b, 0xf5, 0x56, 0x9f, 0xed, 0x9b, 0x58, 0x1f,
	0x5d, 0x8c, 0x25, 0xdc, 0x59, 0x9b, 0xca, 0x23, 0xbe, 0x73, 0x31, 0x47, 0x3f, 0xb0, 0xf4, 0x60,
	0x36, 0x70, 0xd2, 0x7b, 0xb8, 0xfb, 0x51, 0x9d, 0x78, 0x59, 0xa4, 0x8b, 0x67, 0x5f, 0x37, 0xbf,
	0x3e, 0x66, 0x85, 0xce, 0x9b, 0x7d, 0x94, 0x88, 0x63, 0x5c, 0x4b, 0x81, 0xe5, 0x5e, 0x57, 0xb1,
	0x4a, 0x72, 0x21, 0xca, 0x15, 0x9e, 0x70, 0x55, 0xf1, 0x53, 0x11, 0x67, 0x5c, 0xe3, 0x1f, 0x7e,
	0x8e, 0xcd, 0xff, 0xad, 0xe2, 0x56, 0x68, 0x7f, 0x6b, 0x8a, 0xf7, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0xed, 0xad, 0x43, 0x03, 0x03, 0x00, 0x00,
}
