# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import food_pb2 as food__pb2


class FoodStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Search = channel.unary_unary(
        '/Food/Search',
        request_serializer=food__pb2.FoodRequest.SerializeToString,
        response_deserializer=food__pb2.FoodResponse.FromString,
        )


class FoodServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FoodServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=food__pb2.FoodRequest.FromString,
          response_serializer=food__pb2.FoodResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Food', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
