# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: food.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='food.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nfood.proto\"\r\n\x0b\x46oodRequest\"\x1c\n\x0c\x46oodResponse\x12\x0c\n\x04name\x18\x01 \x01(\t2/\n\x04\x46ood\x12\'\n\x06Search\x12\x0c.FoodRequest\x1a\r.FoodResponse\"\x00\x62\x06proto3')
)




_FOODREQUEST = _descriptor.Descriptor(
  name='FoodRequest',
  full_name='FoodRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=27,
)


_FOODRESPONSE = _descriptor.Descriptor(
  name='FoodResponse',
  full_name='FoodResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FoodResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['FoodRequest'] = _FOODREQUEST
DESCRIPTOR.message_types_by_name['FoodResponse'] = _FOODRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FoodRequest = _reflection.GeneratedProtocolMessageType('FoodRequest', (_message.Message,), dict(
  DESCRIPTOR = _FOODREQUEST,
  __module__ = 'food_pb2'
  # @@protoc_insertion_point(class_scope:FoodRequest)
  ))
_sym_db.RegisterMessage(FoodRequest)

FoodResponse = _reflection.GeneratedProtocolMessageType('FoodResponse', (_message.Message,), dict(
  DESCRIPTOR = _FOODRESPONSE,
  __module__ = 'food_pb2'
  # @@protoc_insertion_point(class_scope:FoodResponse)
  ))
_sym_db.RegisterMessage(FoodResponse)



_FOOD = _descriptor.ServiceDescriptor(
  name='Food',
  full_name='Food',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=59,
  serialized_end=106,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='Food.Search',
    index=0,
    containing_service=None,
    input_type=_FOODREQUEST,
    output_type=_FOODRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOOD)

DESCRIPTOR.services_by_name['Food'] = _FOOD

# @@protoc_insertion_point(module_scope)
