# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: food/messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='food/messages.proto',
  package='food',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x66ood/messages.proto\x12\x04\x66ood\"\x14\n\x04\x46ood\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3')
)




_FOOD = _descriptor.Descriptor(
  name='Food',
  full_name='food.Food',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='food.Food.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['Food'] = _FOOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Food = _reflection.GeneratedProtocolMessageType('Food', (_message.Message,), dict(
  DESCRIPTOR = _FOOD,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.Food)
  ))
_sym_db.RegisterMessage(Food)


# @@protoc_insertion_point(module_scope)
