# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from food import messages_pb2 as food_dot_messages__pb2
from food import service_pb2 as food_dot_service__pb2


class FoodServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Search = channel.unary_unary(
        '/food.FoodService/Search',
        request_serializer=food_dot_service__pb2.FoodRequest.SerializeToString,
        response_deserializer=food_dot_messages__pb2.Food.FromString,
        )


class FoodServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FoodServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=food_dot_service__pb2.FoodRequest.FromString,
          response_serializer=food_dot_messages__pb2.Food.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'food.FoodService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
