# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: food/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from food import messages_pb2 as food_dot_messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='food/service.proto',
  package='food',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x66ood/service.proto\x12\x04\x66ood\x1a\x13\x66ood/messages.proto\"\x1b\n\x0b\x46oodRequest\x12\x0c\n\x04name\x18\x01 \x01(\t28\n\x0b\x46oodService\x12)\n\x06Search\x12\x11.food.FoodRequest\x1a\n.food.Food\"\x00\x62\x06proto3')
  ,
  dependencies=[food_dot_messages__pb2.DESCRIPTOR,])




_FOODREQUEST = _descriptor.Descriptor(
  name='FoodRequest',
  full_name='food.FoodRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='food.FoodRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['FoodRequest'] = _FOODREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FoodRequest = _reflection.GeneratedProtocolMessageType('FoodRequest', (_message.Message,), dict(
  DESCRIPTOR = _FOODREQUEST,
  __module__ = 'food.service_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodRequest)
  ))
_sym_db.RegisterMessage(FoodRequest)



_FOODSERVICE = _descriptor.ServiceDescriptor(
  name='FoodService',
  full_name='food.FoodService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=78,
  serialized_end=134,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='food.FoodService.Search',
    index=0,
    containing_service=None,
    input_type=_FOODREQUEST,
    output_type=food_dot_messages__pb2._FOOD,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOODSERVICE)

DESCRIPTOR.services_by_name['FoodService'] = _FOODSERVICE

# @@protoc_insertion_point(module_scope)
