# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: food/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from food import messages_pb2 as food_dot_messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='food/service.proto',
  package='food',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x66ood/service.proto\x12\x04\x66ood\x1a\x13\x66ood/messages.proto29\n\x04\x46ood\x12\x31\n\x06Search\x12\x11.food.FoodRequest\x1a\x12.food.FoodResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[food_dot_messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FOOD = _descriptor.ServiceDescriptor(
  name='Food',
  full_name='food.Food',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=49,
  serialized_end=106,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='food.Food.Search',
    index=0,
    containing_service=None,
    input_type=food_dot_messages__pb2._FOODREQUEST,
    output_type=food_dot_messages__pb2._FOODRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOOD)

DESCRIPTOR.services_by_name['Food'] = _FOOD

# @@protoc_insertion_point(module_scope)
