# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: food/messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='food/messages.proto',
  package='food',
  syntax='proto3',
  serialized_options=_b('Z7github.com/proelbtn/school-eve-navi/gateway/protos/food'),
  serialized_pb=_b('\n\x13\x66ood/messages.proto\x12\x04\x66ood\"%\n\tFoodGenre\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\"6\n\nFoodRecord\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x1c\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0e.food.FoodData\"9\n\x08\x46oodData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x04\x12\x10\n\x08genre_id\x18\x03 \x01(\x04\"/\n\x0f\x46oodCreateQuery\x12\x1c\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0e.food.FoodData\"#\n\x10\x46oodCreateResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1d\n\x0f\x46oodDeleteQuery\x12\n\n\x02id\x18\x01 \x01(\x04\"#\n\x10\x46oodDeleteResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1a\n\x0c\x46oodGetQuery\x12\n\n\x02id\x18\x01 \x01(\x04\"1\n\rFoodGetResult\x12 \n\x06record\x18\x01 \x01(\x0b\x32\x10.food.FoodRecord\"S\n\x0f\x46oodSearchQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\r\n\x05genre\x18\x04 \x01(\x04\"5\n\x10\x46oodSearchResult\x12!\n\x07records\x18\x01 \x03(\x0b\x32\x10.food.FoodRecord\"\x10\n\x0e\x46oodEmptyQuery\"6\n\x13\x46oodGetGenresResult\x12\x1f\n\x06genres\x18\x01 \x03(\x0b\x32\x0f.food.FoodGenreB9Z7github.com/proelbtn/school-eve-navi/gateway/protos/foodb\x06proto3')
)




_FOODGENRE = _descriptor.Descriptor(
  name='FoodGenre',
  full_name='food.FoodGenre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='food.FoodGenre.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='food.FoodGenre.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=66,
)


_FOODRECORD = _descriptor.Descriptor(
  name='FoodRecord',
  full_name='food.FoodRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='food.FoodRecord.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='food.FoodRecord.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=122,
)


_FOODDATA = _descriptor.Descriptor(
  name='FoodData',
  full_name='food.FoodData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='food.FoodData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='food.FoodData.price', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre_id', full_name='food.FoodData.genre_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=181,
)


_FOODCREATEQUERY = _descriptor.Descriptor(
  name='FoodCreateQuery',
  full_name='food.FoodCreateQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='food.FoodCreateQuery.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=230,
)


_FOODCREATERESULT = _descriptor.Descriptor(
  name='FoodCreateResult',
  full_name='food.FoodCreateResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='food.FoodCreateResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=267,
)


_FOODDELETEQUERY = _descriptor.Descriptor(
  name='FoodDeleteQuery',
  full_name='food.FoodDeleteQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='food.FoodDeleteQuery.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=298,
)


_FOODDELETERESULT = _descriptor.Descriptor(
  name='FoodDeleteResult',
  full_name='food.FoodDeleteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='food.FoodDeleteResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=335,
)


_FOODGETQUERY = _descriptor.Descriptor(
  name='FoodGetQuery',
  full_name='food.FoodGetQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='food.FoodGetQuery.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=363,
)


_FOODGETRESULT = _descriptor.Descriptor(
  name='FoodGetResult',
  full_name='food.FoodGetResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='food.FoodGetResult.record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=414,
)


_FOODSEARCHQUERY = _descriptor.Descriptor(
  name='FoodSearchQuery',
  full_name='food.FoodSearchQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='food.FoodSearchQuery.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='food.FoodSearchQuery.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='food.FoodSearchQuery.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre', full_name='food.FoodSearchQuery.genre', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=499,
)


_FOODSEARCHRESULT = _descriptor.Descriptor(
  name='FoodSearchResult',
  full_name='food.FoodSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='food.FoodSearchResult.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=554,
)


_FOODEMPTYQUERY = _descriptor.Descriptor(
  name='FoodEmptyQuery',
  full_name='food.FoodEmptyQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=572,
)


_FOODGETGENRESRESULT = _descriptor.Descriptor(
  name='FoodGetGenresResult',
  full_name='food.FoodGetGenresResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='genres', full_name='food.FoodGetGenresResult.genres', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=628,
)

_FOODRECORD.fields_by_name['data'].message_type = _FOODDATA
_FOODCREATEQUERY.fields_by_name['data'].message_type = _FOODDATA
_FOODGETRESULT.fields_by_name['record'].message_type = _FOODRECORD
_FOODSEARCHRESULT.fields_by_name['records'].message_type = _FOODRECORD
_FOODGETGENRESRESULT.fields_by_name['genres'].message_type = _FOODGENRE
DESCRIPTOR.message_types_by_name['FoodGenre'] = _FOODGENRE
DESCRIPTOR.message_types_by_name['FoodRecord'] = _FOODRECORD
DESCRIPTOR.message_types_by_name['FoodData'] = _FOODDATA
DESCRIPTOR.message_types_by_name['FoodCreateQuery'] = _FOODCREATEQUERY
DESCRIPTOR.message_types_by_name['FoodCreateResult'] = _FOODCREATERESULT
DESCRIPTOR.message_types_by_name['FoodDeleteQuery'] = _FOODDELETEQUERY
DESCRIPTOR.message_types_by_name['FoodDeleteResult'] = _FOODDELETERESULT
DESCRIPTOR.message_types_by_name['FoodGetQuery'] = _FOODGETQUERY
DESCRIPTOR.message_types_by_name['FoodGetResult'] = _FOODGETRESULT
DESCRIPTOR.message_types_by_name['FoodSearchQuery'] = _FOODSEARCHQUERY
DESCRIPTOR.message_types_by_name['FoodSearchResult'] = _FOODSEARCHRESULT
DESCRIPTOR.message_types_by_name['FoodEmptyQuery'] = _FOODEMPTYQUERY
DESCRIPTOR.message_types_by_name['FoodGetGenresResult'] = _FOODGETGENRESRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FoodGenre = _reflection.GeneratedProtocolMessageType('FoodGenre', (_message.Message,), dict(
  DESCRIPTOR = _FOODGENRE,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodGenre)
  ))
_sym_db.RegisterMessage(FoodGenre)

FoodRecord = _reflection.GeneratedProtocolMessageType('FoodRecord', (_message.Message,), dict(
  DESCRIPTOR = _FOODRECORD,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodRecord)
  ))
_sym_db.RegisterMessage(FoodRecord)

FoodData = _reflection.GeneratedProtocolMessageType('FoodData', (_message.Message,), dict(
  DESCRIPTOR = _FOODDATA,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodData)
  ))
_sym_db.RegisterMessage(FoodData)

FoodCreateQuery = _reflection.GeneratedProtocolMessageType('FoodCreateQuery', (_message.Message,), dict(
  DESCRIPTOR = _FOODCREATEQUERY,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodCreateQuery)
  ))
_sym_db.RegisterMessage(FoodCreateQuery)

FoodCreateResult = _reflection.GeneratedProtocolMessageType('FoodCreateResult', (_message.Message,), dict(
  DESCRIPTOR = _FOODCREATERESULT,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodCreateResult)
  ))
_sym_db.RegisterMessage(FoodCreateResult)

FoodDeleteQuery = _reflection.GeneratedProtocolMessageType('FoodDeleteQuery', (_message.Message,), dict(
  DESCRIPTOR = _FOODDELETEQUERY,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodDeleteQuery)
  ))
_sym_db.RegisterMessage(FoodDeleteQuery)

FoodDeleteResult = _reflection.GeneratedProtocolMessageType('FoodDeleteResult', (_message.Message,), dict(
  DESCRIPTOR = _FOODDELETERESULT,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodDeleteResult)
  ))
_sym_db.RegisterMessage(FoodDeleteResult)

FoodGetQuery = _reflection.GeneratedProtocolMessageType('FoodGetQuery', (_message.Message,), dict(
  DESCRIPTOR = _FOODGETQUERY,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodGetQuery)
  ))
_sym_db.RegisterMessage(FoodGetQuery)

FoodGetResult = _reflection.GeneratedProtocolMessageType('FoodGetResult', (_message.Message,), dict(
  DESCRIPTOR = _FOODGETRESULT,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodGetResult)
  ))
_sym_db.RegisterMessage(FoodGetResult)

FoodSearchQuery = _reflection.GeneratedProtocolMessageType('FoodSearchQuery', (_message.Message,), dict(
  DESCRIPTOR = _FOODSEARCHQUERY,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodSearchQuery)
  ))
_sym_db.RegisterMessage(FoodSearchQuery)

FoodSearchResult = _reflection.GeneratedProtocolMessageType('FoodSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _FOODSEARCHRESULT,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodSearchResult)
  ))
_sym_db.RegisterMessage(FoodSearchResult)

FoodEmptyQuery = _reflection.GeneratedProtocolMessageType('FoodEmptyQuery', (_message.Message,), dict(
  DESCRIPTOR = _FOODEMPTYQUERY,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodEmptyQuery)
  ))
_sym_db.RegisterMessage(FoodEmptyQuery)

FoodGetGenresResult = _reflection.GeneratedProtocolMessageType('FoodGetGenresResult', (_message.Message,), dict(
  DESCRIPTOR = _FOODGETGENRESRESULT,
  __module__ = 'food.messages_pb2'
  # @@protoc_insertion_point(class_scope:food.FoodGetGenresResult)
  ))
_sym_db.RegisterMessage(FoodGetGenresResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
