# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: food/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from food import messages_pb2 as food_dot_messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='food/service.proto',
  package='food',
  syntax='proto3',
  serialized_options=_b('Z7github.com/proelbtn/school-eve-navi/gateway/protos/food'),
  serialized_pb=_b('\n\x12\x66ood/service.proto\x12\x04\x66ood\x1a\x13\x66ood/messages.proto2\xa9\x02\n\x04\x46ood\x12\x39\n\x06\x43reate\x12\x15.food.FoodCreateQuery\x1a\x16.food.FoodCreateResult\"\x00\x12\x39\n\x06\x44\x65lete\x12\x15.food.FoodDeleteQuery\x1a\x16.food.FoodDeleteResult\"\x00\x12\x30\n\x03Get\x12\x12.food.FoodGetQuery\x1a\x13.food.FoodGetResult\"\x00\x12\x39\n\x06Search\x12\x15.food.FoodSearchQuery\x1a\x16.food.FoodSearchResult\"\x00\x12>\n\tGetGenres\x12\x14.food.FoodEmptyQuery\x1a\x19.food.FoodGetGenresResult\"\x00\x42\x39Z7github.com/proelbtn/school-eve-navi/gateway/protos/foodb\x06proto3')
  ,
  dependencies=[food_dot_messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_FOOD = _descriptor.ServiceDescriptor(
  name='Food',
  full_name='food.Food',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=50,
  serialized_end=347,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='food.Food.Create',
    index=0,
    containing_service=None,
    input_type=food_dot_messages__pb2._FOODCREATEQUERY,
    output_type=food_dot_messages__pb2._FOODCREATERESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='food.Food.Delete',
    index=1,
    containing_service=None,
    input_type=food_dot_messages__pb2._FOODDELETEQUERY,
    output_type=food_dot_messages__pb2._FOODDELETERESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='food.Food.Get',
    index=2,
    containing_service=None,
    input_type=food_dot_messages__pb2._FOODGETQUERY,
    output_type=food_dot_messages__pb2._FOODGETRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='food.Food.Search',
    index=3,
    containing_service=None,
    input_type=food_dot_messages__pb2._FOODSEARCHQUERY,
    output_type=food_dot_messages__pb2._FOODSEARCHRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetGenres',
    full_name='food.Food.GetGenres',
    index=4,
    containing_service=None,
    input_type=food_dot_messages__pb2._FOODEMPTYQUERY,
    output_type=food_dot_messages__pb2._FOODGETGENRESRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOOD)

DESCRIPTOR.services_by_name['Food'] = _FOOD

# @@protoc_insertion_point(module_scope)
