# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shop/messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shop/messages.proto',
  package='shop',
  syntax='proto3',
  serialized_options=_b('Z7github.com/proelbtn/school-eve-navi/gateway/protos/shop'),
  serialized_pb=_b('\n\x13shop/messages.proto\x12\x04shop\"%\n\tShopGenre\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\"6\n\nShopRecord\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x1c\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0e.shop.ShopData\"}\n\x08ShopData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08genre_id\x18\x03 \x01(\x04\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x10\n\x08latitude\x18\x05 \x01(\x01\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\x12\x0c\n\x04open\x18\x07 \x01(\x04\x12\r\n\x05\x63lose\x18\x08 \x01(\x04\"/\n\x0fShopCreateQuery\x12\x1c\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0e.shop.ShopData\"#\n\x10ShopCreateResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1d\n\x0fShopDeleteQuery\x12\n\n\x02id\x18\x01 \x01(\x04\"#\n\x10ShopDeleteResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1a\n\x0cShopGetQuery\x12\n\n\x02id\x18\x01 \x01(\x04\"1\n\rShopGetResult\x12 \n\x06record\x18\x01 \x01(\x0b\x32\x10.shop.ShopRecord\"1\n\x0fShopSearchQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08genre_id\x18\x04 \x01(\x04\"5\n\x10ShopSearchResult\x12!\n\x07records\x18\x01 \x03(\x0b\x32\x10.shop.ShopRecord\"\x10\n\x0eShopEmptyQuery\"6\n\x13ShopGetGenresResult\x12\x1f\n\x06genres\x18\x01 \x03(\x0b\x32\x0f.shop.ShopGenreB9Z7github.com/proelbtn/school-eve-navi/gateway/protos/shopb\x06proto3')
)




_SHOPGENRE = _descriptor.Descriptor(
  name='ShopGenre',
  full_name='shop.ShopGenre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='shop.ShopGenre.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='shop.ShopGenre.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=66,
)


_SHOPRECORD = _descriptor.Descriptor(
  name='ShopRecord',
  full_name='shop.ShopRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='shop.ShopRecord.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='shop.ShopRecord.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=122,
)


_SHOPDATA = _descriptor.Descriptor(
  name='ShopData',
  full_name='shop.ShopData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='shop.ShopData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre_id', full_name='shop.ShopData.genre_id', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='shop.ShopData.longitude', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='shop.ShopData.latitude', index=3,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='shop.ShopData.address', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open', full_name='shop.ShopData.open', index=5,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='shop.ShopData.close', index=6,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=249,
)


_SHOPCREATEQUERY = _descriptor.Descriptor(
  name='ShopCreateQuery',
  full_name='shop.ShopCreateQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='shop.ShopCreateQuery.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=298,
)


_SHOPCREATERESULT = _descriptor.Descriptor(
  name='ShopCreateResult',
  full_name='shop.ShopCreateResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='shop.ShopCreateResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=335,
)


_SHOPDELETEQUERY = _descriptor.Descriptor(
  name='ShopDeleteQuery',
  full_name='shop.ShopDeleteQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='shop.ShopDeleteQuery.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=366,
)


_SHOPDELETERESULT = _descriptor.Descriptor(
  name='ShopDeleteResult',
  full_name='shop.ShopDeleteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='shop.ShopDeleteResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=403,
)


_SHOPGETQUERY = _descriptor.Descriptor(
  name='ShopGetQuery',
  full_name='shop.ShopGetQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='shop.ShopGetQuery.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=431,
)


_SHOPGETRESULT = _descriptor.Descriptor(
  name='ShopGetResult',
  full_name='shop.ShopGetResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='shop.ShopGetResult.record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=482,
)


_SHOPSEARCHQUERY = _descriptor.Descriptor(
  name='ShopSearchQuery',
  full_name='shop.ShopSearchQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='shop.ShopSearchQuery.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre_id', full_name='shop.ShopSearchQuery.genre_id', index=1,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=533,
)


_SHOPSEARCHRESULT = _descriptor.Descriptor(
  name='ShopSearchResult',
  full_name='shop.ShopSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='shop.ShopSearchResult.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=588,
)


_SHOPEMPTYQUERY = _descriptor.Descriptor(
  name='ShopEmptyQuery',
  full_name='shop.ShopEmptyQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=590,
  serialized_end=606,
)


_SHOPGETGENRESRESULT = _descriptor.Descriptor(
  name='ShopGetGenresResult',
  full_name='shop.ShopGetGenresResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='genres', full_name='shop.ShopGetGenresResult.genres', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=608,
  serialized_end=662,
)

_SHOPRECORD.fields_by_name['data'].message_type = _SHOPDATA
_SHOPCREATEQUERY.fields_by_name['data'].message_type = _SHOPDATA
_SHOPGETRESULT.fields_by_name['record'].message_type = _SHOPRECORD
_SHOPSEARCHRESULT.fields_by_name['records'].message_type = _SHOPRECORD
_SHOPGETGENRESRESULT.fields_by_name['genres'].message_type = _SHOPGENRE
DESCRIPTOR.message_types_by_name['ShopGenre'] = _SHOPGENRE
DESCRIPTOR.message_types_by_name['ShopRecord'] = _SHOPRECORD
DESCRIPTOR.message_types_by_name['ShopData'] = _SHOPDATA
DESCRIPTOR.message_types_by_name['ShopCreateQuery'] = _SHOPCREATEQUERY
DESCRIPTOR.message_types_by_name['ShopCreateResult'] = _SHOPCREATERESULT
DESCRIPTOR.message_types_by_name['ShopDeleteQuery'] = _SHOPDELETEQUERY
DESCRIPTOR.message_types_by_name['ShopDeleteResult'] = _SHOPDELETERESULT
DESCRIPTOR.message_types_by_name['ShopGetQuery'] = _SHOPGETQUERY
DESCRIPTOR.message_types_by_name['ShopGetResult'] = _SHOPGETRESULT
DESCRIPTOR.message_types_by_name['ShopSearchQuery'] = _SHOPSEARCHQUERY
DESCRIPTOR.message_types_by_name['ShopSearchResult'] = _SHOPSEARCHRESULT
DESCRIPTOR.message_types_by_name['ShopEmptyQuery'] = _SHOPEMPTYQUERY
DESCRIPTOR.message_types_by_name['ShopGetGenresResult'] = _SHOPGETGENRESRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShopGenre = _reflection.GeneratedProtocolMessageType('ShopGenre', (_message.Message,), dict(
  DESCRIPTOR = _SHOPGENRE,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopGenre)
  ))
_sym_db.RegisterMessage(ShopGenre)

ShopRecord = _reflection.GeneratedProtocolMessageType('ShopRecord', (_message.Message,), dict(
  DESCRIPTOR = _SHOPRECORD,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopRecord)
  ))
_sym_db.RegisterMessage(ShopRecord)

ShopData = _reflection.GeneratedProtocolMessageType('ShopData', (_message.Message,), dict(
  DESCRIPTOR = _SHOPDATA,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopData)
  ))
_sym_db.RegisterMessage(ShopData)

ShopCreateQuery = _reflection.GeneratedProtocolMessageType('ShopCreateQuery', (_message.Message,), dict(
  DESCRIPTOR = _SHOPCREATEQUERY,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopCreateQuery)
  ))
_sym_db.RegisterMessage(ShopCreateQuery)

ShopCreateResult = _reflection.GeneratedProtocolMessageType('ShopCreateResult', (_message.Message,), dict(
  DESCRIPTOR = _SHOPCREATERESULT,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopCreateResult)
  ))
_sym_db.RegisterMessage(ShopCreateResult)

ShopDeleteQuery = _reflection.GeneratedProtocolMessageType('ShopDeleteQuery', (_message.Message,), dict(
  DESCRIPTOR = _SHOPDELETEQUERY,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopDeleteQuery)
  ))
_sym_db.RegisterMessage(ShopDeleteQuery)

ShopDeleteResult = _reflection.GeneratedProtocolMessageType('ShopDeleteResult', (_message.Message,), dict(
  DESCRIPTOR = _SHOPDELETERESULT,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopDeleteResult)
  ))
_sym_db.RegisterMessage(ShopDeleteResult)

ShopGetQuery = _reflection.GeneratedProtocolMessageType('ShopGetQuery', (_message.Message,), dict(
  DESCRIPTOR = _SHOPGETQUERY,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopGetQuery)
  ))
_sym_db.RegisterMessage(ShopGetQuery)

ShopGetResult = _reflection.GeneratedProtocolMessageType('ShopGetResult', (_message.Message,), dict(
  DESCRIPTOR = _SHOPGETRESULT,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopGetResult)
  ))
_sym_db.RegisterMessage(ShopGetResult)

ShopSearchQuery = _reflection.GeneratedProtocolMessageType('ShopSearchQuery', (_message.Message,), dict(
  DESCRIPTOR = _SHOPSEARCHQUERY,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopSearchQuery)
  ))
_sym_db.RegisterMessage(ShopSearchQuery)

ShopSearchResult = _reflection.GeneratedProtocolMessageType('ShopSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _SHOPSEARCHRESULT,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopSearchResult)
  ))
_sym_db.RegisterMessage(ShopSearchResult)

ShopEmptyQuery = _reflection.GeneratedProtocolMessageType('ShopEmptyQuery', (_message.Message,), dict(
  DESCRIPTOR = _SHOPEMPTYQUERY,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopEmptyQuery)
  ))
_sym_db.RegisterMessage(ShopEmptyQuery)

ShopGetGenresResult = _reflection.GeneratedProtocolMessageType('ShopGetGenresResult', (_message.Message,), dict(
  DESCRIPTOR = _SHOPGETGENRESRESULT,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopGetGenresResult)
  ))
_sym_db.RegisterMessage(ShopGetGenresResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
