# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shop/messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shop/messages.proto',
  package='shop',
  syntax='proto3',
  serialized_options=_b('Z7github.com/proelbtn/school-eve-navi/gateway/protos/shop'),
  serialized_pb=_b('\n\x13shop/messages.proto\x12\x04shop\"6\n\nShopRecord\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x1c\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0e.shop.ShopData\"G\n\x08ShopData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x04\x12\x1e\n\x05genre\x18\x03 \x01(\x0e\x32\x0f.shop.ShopGenre\"/\n\x0fShopCreateQuery\x12\x1c\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0e.shop.ShopData\"4\n\x10ShopCreateResult\x12 \n\x06record\x18\x01 \x01(\x0b\x32\x10.shop.ShopRecord\"\x1d\n\x0fShopDeleteQuery\x12\n\n\x02id\x18\x01 \x01(\x03\"$\n\x10ShopDeleteResult\x12\x10\n\x08\x61\x66\x66\x65\x63ted\x18\x01 \x01(\x03\"\x1a\n\x0cShopGetQuery\x12\n\n\x02id\x18\x01 \x01(\x03\"1\n\rShopGetResult\x12 \n\x06record\x18\x01 \x01(\x0b\x32\x10.shop.ShopRecord\"d\n\x0fShopSearchQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x1e\n\x05genre\x18\x04 \x01(\x0e\x32\x0f.shop.ShopGenre\"5\n\x10ShopSearchResult\x12!\n\x07records\x18\x01 \x03(\x0b\x32\x10.shop.ShopRecord*\x18\n\tShopGenre\x12\x0b\n\x07Invalid\x10\x00\x42\x39Z7github.com/proelbtn/school-eve-navi/gateway/protos/shopb\x06proto3')
)

_SHOPGENRE = _descriptor.EnumDescriptor(
  name='ShopGenre',
  full_name='shop.ShopGenre',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Invalid', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=566,
  serialized_end=590,
)
_sym_db.RegisterEnumDescriptor(_SHOPGENRE)

ShopGenre = enum_type_wrapper.EnumTypeWrapper(_SHOPGENRE)
Invalid = 0



_SHOPRECORD = _descriptor.Descriptor(
  name='ShopRecord',
  full_name='shop.ShopRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='shop.ShopRecord.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='shop.ShopRecord.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=83,
)


_SHOPDATA = _descriptor.Descriptor(
  name='ShopData',
  full_name='shop.ShopData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='shop.ShopData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='shop.ShopData.price', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre', full_name='shop.ShopData.genre', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=156,
)


_SHOPCREATEQUERY = _descriptor.Descriptor(
  name='ShopCreateQuery',
  full_name='shop.ShopCreateQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='shop.ShopCreateQuery.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=205,
)


_SHOPCREATERESULT = _descriptor.Descriptor(
  name='ShopCreateResult',
  full_name='shop.ShopCreateResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='shop.ShopCreateResult.record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=259,
)


_SHOPDELETEQUERY = _descriptor.Descriptor(
  name='ShopDeleteQuery',
  full_name='shop.ShopDeleteQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='shop.ShopDeleteQuery.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=290,
)


_SHOPDELETERESULT = _descriptor.Descriptor(
  name='ShopDeleteResult',
  full_name='shop.ShopDeleteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='affected', full_name='shop.ShopDeleteResult.affected', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=328,
)


_SHOPGETQUERY = _descriptor.Descriptor(
  name='ShopGetQuery',
  full_name='shop.ShopGetQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='shop.ShopGetQuery.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=356,
)


_SHOPGETRESULT = _descriptor.Descriptor(
  name='ShopGetResult',
  full_name='shop.ShopGetResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='shop.ShopGetResult.record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=407,
)


_SHOPSEARCHQUERY = _descriptor.Descriptor(
  name='ShopSearchQuery',
  full_name='shop.ShopSearchQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='shop.ShopSearchQuery.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='shop.ShopSearchQuery.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='shop.ShopSearchQuery.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre', full_name='shop.ShopSearchQuery.genre', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=509,
)


_SHOPSEARCHRESULT = _descriptor.Descriptor(
  name='ShopSearchResult',
  full_name='shop.ShopSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='shop.ShopSearchResult.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=564,
)

_SHOPRECORD.fields_by_name['data'].message_type = _SHOPDATA
_SHOPDATA.fields_by_name['genre'].enum_type = _SHOPGENRE
_SHOPCREATEQUERY.fields_by_name['data'].message_type = _SHOPDATA
_SHOPCREATERESULT.fields_by_name['record'].message_type = _SHOPRECORD
_SHOPGETRESULT.fields_by_name['record'].message_type = _SHOPRECORD
_SHOPSEARCHQUERY.fields_by_name['genre'].enum_type = _SHOPGENRE
_SHOPSEARCHRESULT.fields_by_name['records'].message_type = _SHOPRECORD
DESCRIPTOR.message_types_by_name['ShopRecord'] = _SHOPRECORD
DESCRIPTOR.message_types_by_name['ShopData'] = _SHOPDATA
DESCRIPTOR.message_types_by_name['ShopCreateQuery'] = _SHOPCREATEQUERY
DESCRIPTOR.message_types_by_name['ShopCreateResult'] = _SHOPCREATERESULT
DESCRIPTOR.message_types_by_name['ShopDeleteQuery'] = _SHOPDELETEQUERY
DESCRIPTOR.message_types_by_name['ShopDeleteResult'] = _SHOPDELETERESULT
DESCRIPTOR.message_types_by_name['ShopGetQuery'] = _SHOPGETQUERY
DESCRIPTOR.message_types_by_name['ShopGetResult'] = _SHOPGETRESULT
DESCRIPTOR.message_types_by_name['ShopSearchQuery'] = _SHOPSEARCHQUERY
DESCRIPTOR.message_types_by_name['ShopSearchResult'] = _SHOPSEARCHRESULT
DESCRIPTOR.enum_types_by_name['ShopGenre'] = _SHOPGENRE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShopRecord = _reflection.GeneratedProtocolMessageType('ShopRecord', (_message.Message,), dict(
  DESCRIPTOR = _SHOPRECORD,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopRecord)
  ))
_sym_db.RegisterMessage(ShopRecord)

ShopData = _reflection.GeneratedProtocolMessageType('ShopData', (_message.Message,), dict(
  DESCRIPTOR = _SHOPDATA,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopData)
  ))
_sym_db.RegisterMessage(ShopData)

ShopCreateQuery = _reflection.GeneratedProtocolMessageType('ShopCreateQuery', (_message.Message,), dict(
  DESCRIPTOR = _SHOPCREATEQUERY,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopCreateQuery)
  ))
_sym_db.RegisterMessage(ShopCreateQuery)

ShopCreateResult = _reflection.GeneratedProtocolMessageType('ShopCreateResult', (_message.Message,), dict(
  DESCRIPTOR = _SHOPCREATERESULT,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopCreateResult)
  ))
_sym_db.RegisterMessage(ShopCreateResult)

ShopDeleteQuery = _reflection.GeneratedProtocolMessageType('ShopDeleteQuery', (_message.Message,), dict(
  DESCRIPTOR = _SHOPDELETEQUERY,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopDeleteQuery)
  ))
_sym_db.RegisterMessage(ShopDeleteQuery)

ShopDeleteResult = _reflection.GeneratedProtocolMessageType('ShopDeleteResult', (_message.Message,), dict(
  DESCRIPTOR = _SHOPDELETERESULT,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopDeleteResult)
  ))
_sym_db.RegisterMessage(ShopDeleteResult)

ShopGetQuery = _reflection.GeneratedProtocolMessageType('ShopGetQuery', (_message.Message,), dict(
  DESCRIPTOR = _SHOPGETQUERY,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopGetQuery)
  ))
_sym_db.RegisterMessage(ShopGetQuery)

ShopGetResult = _reflection.GeneratedProtocolMessageType('ShopGetResult', (_message.Message,), dict(
  DESCRIPTOR = _SHOPGETRESULT,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopGetResult)
  ))
_sym_db.RegisterMessage(ShopGetResult)

ShopSearchQuery = _reflection.GeneratedProtocolMessageType('ShopSearchQuery', (_message.Message,), dict(
  DESCRIPTOR = _SHOPSEARCHQUERY,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopSearchQuery)
  ))
_sym_db.RegisterMessage(ShopSearchQuery)

ShopSearchResult = _reflection.GeneratedProtocolMessageType('ShopSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _SHOPSEARCHRESULT,
  __module__ = 'shop.messages_pb2'
  # @@protoc_insertion_point(class_scope:shop.ShopSearchResult)
  ))
_sym_db.RegisterMessage(ShopSearchResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
