# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shop/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shop import messages_pb2 as shop_dot_messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shop/service.proto',
  package='shop',
  syntax='proto3',
  serialized_options=_b('Z7github.com/proelbtn/school-eve-navi/gateway/protos/shop'),
  serialized_pb=_b('\n\x12shop/service.proto\x12\x04shop\x1a\x13shop/messages.proto2\xa9\x02\n\x04Shop\x12\x39\n\x06\x43reate\x12\x15.shop.ShopCreateQuery\x1a\x16.shop.ShopCreateResult\"\x00\x12\x39\n\x06\x44\x65lete\x12\x15.shop.ShopDeleteQuery\x1a\x16.shop.ShopDeleteResult\"\x00\x12\x30\n\x03Get\x12\x12.shop.ShopGetQuery\x1a\x13.shop.ShopGetResult\"\x00\x12\x39\n\x06Search\x12\x15.shop.ShopSearchQuery\x1a\x16.shop.ShopSearchResult\"\x00\x12>\n\tGetGenres\x12\x14.shop.ShopEmptyQuery\x1a\x19.shop.ShopGetGenresResult\"\x00\x42\x39Z7github.com/proelbtn/school-eve-navi/gateway/protos/shopb\x06proto3')
  ,
  dependencies=[shop_dot_messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_SHOP = _descriptor.ServiceDescriptor(
  name='Shop',
  full_name='shop.Shop',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=50,
  serialized_end=347,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='shop.Shop.Create',
    index=0,
    containing_service=None,
    input_type=shop_dot_messages__pb2._SHOPCREATEQUERY,
    output_type=shop_dot_messages__pb2._SHOPCREATERESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='shop.Shop.Delete',
    index=1,
    containing_service=None,
    input_type=shop_dot_messages__pb2._SHOPDELETEQUERY,
    output_type=shop_dot_messages__pb2._SHOPDELETERESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='shop.Shop.Get',
    index=2,
    containing_service=None,
    input_type=shop_dot_messages__pb2._SHOPGETQUERY,
    output_type=shop_dot_messages__pb2._SHOPGETRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='shop.Shop.Search',
    index=3,
    containing_service=None,
    input_type=shop_dot_messages__pb2._SHOPSEARCHQUERY,
    output_type=shop_dot_messages__pb2._SHOPSEARCHRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetGenres',
    full_name='shop.Shop.GetGenres',
    index=4,
    containing_service=None,
    input_type=shop_dot_messages__pb2._SHOPEMPTYQUERY,
    output_type=shop_dot_messages__pb2._SHOPGETGENRESRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOP)

DESCRIPTOR.services_by_name['Shop'] = _SHOP

# @@protoc_insertion_point(module_scope)
