# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from shop import messages_pb2 as shop_dot_messages__pb2


class ShopStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/shop.Shop/Create',
        request_serializer=shop_dot_messages__pb2.ShopCreateQuery.SerializeToString,
        response_deserializer=shop_dot_messages__pb2.ShopCreateResult.FromString,
        )
    self.Delete = channel.unary_unary(
        '/shop.Shop/Delete',
        request_serializer=shop_dot_messages__pb2.ShopDeleteQuery.SerializeToString,
        response_deserializer=shop_dot_messages__pb2.ShopDeleteResult.FromString,
        )
    self.Get = channel.unary_unary(
        '/shop.Shop/Get',
        request_serializer=shop_dot_messages__pb2.ShopGetQuery.SerializeToString,
        response_deserializer=shop_dot_messages__pb2.ShopGetResult.FromString,
        )
    self.Search = channel.unary_unary(
        '/shop.Shop/Search',
        request_serializer=shop_dot_messages__pb2.ShopSearchQuery.SerializeToString,
        response_deserializer=shop_dot_messages__pb2.ShopSearchResult.FromString,
        )
    self.GetGenres = channel.unary_unary(
        '/shop.Shop/GetGenres',
        request_serializer=shop_dot_messages__pb2.ShopEmptyQuery.SerializeToString,
        response_deserializer=shop_dot_messages__pb2.ShopGetGenresResult.FromString,
        )


class ShopServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGenres(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ShopServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=shop_dot_messages__pb2.ShopCreateQuery.FromString,
          response_serializer=shop_dot_messages__pb2.ShopCreateResult.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=shop_dot_messages__pb2.ShopDeleteQuery.FromString,
          response_serializer=shop_dot_messages__pb2.ShopDeleteResult.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=shop_dot_messages__pb2.ShopGetQuery.FromString,
          response_serializer=shop_dot_messages__pb2.ShopGetResult.SerializeToString,
      ),
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=shop_dot_messages__pb2.ShopSearchQuery.FromString,
          response_serializer=shop_dot_messages__pb2.ShopSearchResult.SerializeToString,
      ),
      'GetGenres': grpc.unary_unary_rpc_method_handler(
          servicer.GetGenres,
          request_deserializer=shop_dot_messages__pb2.ShopEmptyQuery.FromString,
          response_serializer=shop_dot_messages__pb2.ShopGetGenresResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'shop.Shop', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
