# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: souvenir/messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='souvenir/messages.proto',
  package='souvenir',
  syntax='proto3',
  serialized_options=_b('Z;github.com/proelbtn/school-eve-navi/gateway/protos/souvenir'),
  serialized_pb=_b('\n\x17souvenir/messages.proto\x12\x08souvenir\")\n\rSouvenirGenre\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\"B\n\x0eSouvenirRecord\x12\n\n\x02id\x18\x01 \x01(\x04\x12$\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x16.souvenir.SouvenirData\"=\n\x0cSouvenirData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x04\x12\x10\n\x08genre_id\x18\x03 \x01(\x04\";\n\x13SouvenirCreateQuery\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.souvenir.SouvenirData\"\'\n\x14SouvenirCreateResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x13SouvenirDeleteQuery\x12\n\n\x02id\x18\x01 \x01(\x04\"\'\n\x14SouvenirDeleteResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x10SouvenirGetQuery\x12\n\n\x02id\x18\x01 \x01(\x04\"=\n\x11SouvenirGetResult\x12(\n\x06record\x18\x01 \x01(\x0b\x32\x18.souvenir.SouvenirRecord\"5\n\x13SouvenirSearchQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08genre_id\x18\x04 \x01(\x04\"A\n\x14SouvenirSearchResult\x12)\n\x07records\x18\x01 \x03(\x0b\x32\x18.souvenir.SouvenirRecord\"\x14\n\x12SouvenirEmptyQuery\"B\n\x17SouvenirGetGenresResult\x12\'\n\x06genres\x18\x01 \x03(\x0b\x32\x17.souvenir.SouvenirGenreB=Z;github.com/proelbtn/school-eve-navi/gateway/protos/souvenirb\x06proto3')
)




_SOUVENIRGENRE = _descriptor.Descriptor(
  name='SouvenirGenre',
  full_name='souvenir.SouvenirGenre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='souvenir.SouvenirGenre.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='souvenir.SouvenirGenre.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=78,
)


_SOUVENIRRECORD = _descriptor.Descriptor(
  name='SouvenirRecord',
  full_name='souvenir.SouvenirRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='souvenir.SouvenirRecord.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='souvenir.SouvenirRecord.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=146,
)


_SOUVENIRDATA = _descriptor.Descriptor(
  name='SouvenirData',
  full_name='souvenir.SouvenirData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='souvenir.SouvenirData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='souvenir.SouvenirData.price', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre_id', full_name='souvenir.SouvenirData.genre_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=209,
)


_SOUVENIRCREATEQUERY = _descriptor.Descriptor(
  name='SouvenirCreateQuery',
  full_name='souvenir.SouvenirCreateQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='souvenir.SouvenirCreateQuery.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=270,
)


_SOUVENIRCREATERESULT = _descriptor.Descriptor(
  name='SouvenirCreateResult',
  full_name='souvenir.SouvenirCreateResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='souvenir.SouvenirCreateResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=311,
)


_SOUVENIRDELETEQUERY = _descriptor.Descriptor(
  name='SouvenirDeleteQuery',
  full_name='souvenir.SouvenirDeleteQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='souvenir.SouvenirDeleteQuery.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=346,
)


_SOUVENIRDELETERESULT = _descriptor.Descriptor(
  name='SouvenirDeleteResult',
  full_name='souvenir.SouvenirDeleteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='souvenir.SouvenirDeleteResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=387,
)


_SOUVENIRGETQUERY = _descriptor.Descriptor(
  name='SouvenirGetQuery',
  full_name='souvenir.SouvenirGetQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='souvenir.SouvenirGetQuery.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=419,
)


_SOUVENIRGETRESULT = _descriptor.Descriptor(
  name='SouvenirGetResult',
  full_name='souvenir.SouvenirGetResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='souvenir.SouvenirGetResult.record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=482,
)


_SOUVENIRSEARCHQUERY = _descriptor.Descriptor(
  name='SouvenirSearchQuery',
  full_name='souvenir.SouvenirSearchQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='souvenir.SouvenirSearchQuery.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre_id', full_name='souvenir.SouvenirSearchQuery.genre_id', index=1,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=537,
)


_SOUVENIRSEARCHRESULT = _descriptor.Descriptor(
  name='SouvenirSearchResult',
  full_name='souvenir.SouvenirSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='souvenir.SouvenirSearchResult.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=604,
)


_SOUVENIREMPTYQUERY = _descriptor.Descriptor(
  name='SouvenirEmptyQuery',
  full_name='souvenir.SouvenirEmptyQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=606,
  serialized_end=626,
)


_SOUVENIRGETGENRESRESULT = _descriptor.Descriptor(
  name='SouvenirGetGenresResult',
  full_name='souvenir.SouvenirGetGenresResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='genres', full_name='souvenir.SouvenirGetGenresResult.genres', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=628,
  serialized_end=694,
)

_SOUVENIRRECORD.fields_by_name['data'].message_type = _SOUVENIRDATA
_SOUVENIRCREATEQUERY.fields_by_name['data'].message_type = _SOUVENIRDATA
_SOUVENIRGETRESULT.fields_by_name['record'].message_type = _SOUVENIRRECORD
_SOUVENIRSEARCHRESULT.fields_by_name['records'].message_type = _SOUVENIRRECORD
_SOUVENIRGETGENRESRESULT.fields_by_name['genres'].message_type = _SOUVENIRGENRE
DESCRIPTOR.message_types_by_name['SouvenirGenre'] = _SOUVENIRGENRE
DESCRIPTOR.message_types_by_name['SouvenirRecord'] = _SOUVENIRRECORD
DESCRIPTOR.message_types_by_name['SouvenirData'] = _SOUVENIRDATA
DESCRIPTOR.message_types_by_name['SouvenirCreateQuery'] = _SOUVENIRCREATEQUERY
DESCRIPTOR.message_types_by_name['SouvenirCreateResult'] = _SOUVENIRCREATERESULT
DESCRIPTOR.message_types_by_name['SouvenirDeleteQuery'] = _SOUVENIRDELETEQUERY
DESCRIPTOR.message_types_by_name['SouvenirDeleteResult'] = _SOUVENIRDELETERESULT
DESCRIPTOR.message_types_by_name['SouvenirGetQuery'] = _SOUVENIRGETQUERY
DESCRIPTOR.message_types_by_name['SouvenirGetResult'] = _SOUVENIRGETRESULT
DESCRIPTOR.message_types_by_name['SouvenirSearchQuery'] = _SOUVENIRSEARCHQUERY
DESCRIPTOR.message_types_by_name['SouvenirSearchResult'] = _SOUVENIRSEARCHRESULT
DESCRIPTOR.message_types_by_name['SouvenirEmptyQuery'] = _SOUVENIREMPTYQUERY
DESCRIPTOR.message_types_by_name['SouvenirGetGenresResult'] = _SOUVENIRGETGENRESRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SouvenirGenre = _reflection.GeneratedProtocolMessageType('SouvenirGenre', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRGENRE,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirGenre)
  ))
_sym_db.RegisterMessage(SouvenirGenre)

SouvenirRecord = _reflection.GeneratedProtocolMessageType('SouvenirRecord', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRRECORD,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirRecord)
  ))
_sym_db.RegisterMessage(SouvenirRecord)

SouvenirData = _reflection.GeneratedProtocolMessageType('SouvenirData', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRDATA,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirData)
  ))
_sym_db.RegisterMessage(SouvenirData)

SouvenirCreateQuery = _reflection.GeneratedProtocolMessageType('SouvenirCreateQuery', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRCREATEQUERY,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirCreateQuery)
  ))
_sym_db.RegisterMessage(SouvenirCreateQuery)

SouvenirCreateResult = _reflection.GeneratedProtocolMessageType('SouvenirCreateResult', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRCREATERESULT,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirCreateResult)
  ))
_sym_db.RegisterMessage(SouvenirCreateResult)

SouvenirDeleteQuery = _reflection.GeneratedProtocolMessageType('SouvenirDeleteQuery', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRDELETEQUERY,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirDeleteQuery)
  ))
_sym_db.RegisterMessage(SouvenirDeleteQuery)

SouvenirDeleteResult = _reflection.GeneratedProtocolMessageType('SouvenirDeleteResult', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRDELETERESULT,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirDeleteResult)
  ))
_sym_db.RegisterMessage(SouvenirDeleteResult)

SouvenirGetQuery = _reflection.GeneratedProtocolMessageType('SouvenirGetQuery', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRGETQUERY,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirGetQuery)
  ))
_sym_db.RegisterMessage(SouvenirGetQuery)

SouvenirGetResult = _reflection.GeneratedProtocolMessageType('SouvenirGetResult', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRGETRESULT,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirGetResult)
  ))
_sym_db.RegisterMessage(SouvenirGetResult)

SouvenirSearchQuery = _reflection.GeneratedProtocolMessageType('SouvenirSearchQuery', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRSEARCHQUERY,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirSearchQuery)
  ))
_sym_db.RegisterMessage(SouvenirSearchQuery)

SouvenirSearchResult = _reflection.GeneratedProtocolMessageType('SouvenirSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRSEARCHRESULT,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirSearchResult)
  ))
_sym_db.RegisterMessage(SouvenirSearchResult)

SouvenirEmptyQuery = _reflection.GeneratedProtocolMessageType('SouvenirEmptyQuery', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIREMPTYQUERY,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirEmptyQuery)
  ))
_sym_db.RegisterMessage(SouvenirEmptyQuery)

SouvenirGetGenresResult = _reflection.GeneratedProtocolMessageType('SouvenirGetGenresResult', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRGETGENRESRESULT,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirGetGenresResult)
  ))
_sym_db.RegisterMessage(SouvenirGetGenresResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
