# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: souvenir/messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='souvenir/messages.proto',
  package='souvenir',
  syntax='proto3',
  serialized_options=_b('Z;github.com/proelbtn/school-eve-navi/gateway/protos/souvenir'),
  serialized_pb=_b('\n\x17souvenir/messages.proto\x12\x08souvenir\"B\n\x0eSouvenirRecord\x12\n\n\x02id\x18\x01 \x01(\x03\x12$\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x16.souvenir.SouvenirData\"S\n\x0cSouvenirData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x04\x12&\n\x05genre\x18\x03 \x01(\x0e\x32\x17.souvenir.SouvenirGenre\";\n\x13SouvenirCreateQuery\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.souvenir.SouvenirData\"@\n\x14SouvenirCreateResult\x12(\n\x06record\x18\x01 \x01(\x0b\x32\x18.souvenir.SouvenirRecord\"!\n\x13SouvenirDeleteQuery\x12\n\n\x02id\x18\x01 \x01(\x03\"(\n\x14SouvenirDeleteResult\x12\x10\n\x08\x61\x66\x66\x65\x63ted\x18\x01 \x01(\x03\"\x1e\n\x10SouvenirGetQuery\x12\n\n\x02id\x18\x01 \x01(\x03\"=\n\x11SouvenirGetResult\x12(\n\x06record\x18\x01 \x01(\x0b\x32\x18.souvenir.SouvenirRecord\"p\n\x13SouvenirSearchQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12&\n\x05genre\x18\x04 \x01(\x0e\x32\x17.souvenir.SouvenirGenre\"A\n\x14SouvenirSearchResult\x12)\n\x07records\x18\x01 \x03(\x0b\x32\x18.souvenir.SouvenirRecord*{\n\rSouvenirGenre\x12\x0b\n\x07Invalid\x10\x00\x12\r\n\tJapaneses\x10\x01\x12\x0c\n\x08Westerns\x10\x02\x12\x0c\n\x08\x43hineses\x10\x03\x12\n\n\x06Sweets\x10\x04\x12\n\n\x06Snacks\x10\x05\x12\x0e\n\nLightMeals\x10\x06\x12\n\n\x06\x44rinks\x10\x07\x42=Z;github.com/proelbtn/school-eve-navi/gateway/protos/souvenirb\x06proto3')
)

_SOUVENIRGENRE = _descriptor.EnumDescriptor(
  name='SouvenirGenre',
  full_name='souvenir.SouvenirGenre',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Invalid', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Japaneses', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Westerns', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Chineses', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sweets', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Snacks', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LightMeals', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Drinks', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=670,
  serialized_end=793,
)
_sym_db.RegisterEnumDescriptor(_SOUVENIRGENRE)

SouvenirGenre = enum_type_wrapper.EnumTypeWrapper(_SOUVENIRGENRE)
Invalid = 0
Japaneses = 1
Westerns = 2
Chineses = 3
Sweets = 4
Snacks = 5
LightMeals = 6
Drinks = 7



_SOUVENIRRECORD = _descriptor.Descriptor(
  name='SouvenirRecord',
  full_name='souvenir.SouvenirRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='souvenir.SouvenirRecord.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='souvenir.SouvenirRecord.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=103,
)


_SOUVENIRDATA = _descriptor.Descriptor(
  name='SouvenirData',
  full_name='souvenir.SouvenirData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='souvenir.SouvenirData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='souvenir.SouvenirData.price', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre', full_name='souvenir.SouvenirData.genre', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=188,
)


_SOUVENIRCREATEQUERY = _descriptor.Descriptor(
  name='SouvenirCreateQuery',
  full_name='souvenir.SouvenirCreateQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='souvenir.SouvenirCreateQuery.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=249,
)


_SOUVENIRCREATERESULT = _descriptor.Descriptor(
  name='SouvenirCreateResult',
  full_name='souvenir.SouvenirCreateResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='souvenir.SouvenirCreateResult.record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=315,
)


_SOUVENIRDELETEQUERY = _descriptor.Descriptor(
  name='SouvenirDeleteQuery',
  full_name='souvenir.SouvenirDeleteQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='souvenir.SouvenirDeleteQuery.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=350,
)


_SOUVENIRDELETERESULT = _descriptor.Descriptor(
  name='SouvenirDeleteResult',
  full_name='souvenir.SouvenirDeleteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='affected', full_name='souvenir.SouvenirDeleteResult.affected', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=392,
)


_SOUVENIRGETQUERY = _descriptor.Descriptor(
  name='SouvenirGetQuery',
  full_name='souvenir.SouvenirGetQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='souvenir.SouvenirGetQuery.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=424,
)


_SOUVENIRGETRESULT = _descriptor.Descriptor(
  name='SouvenirGetResult',
  full_name='souvenir.SouvenirGetResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='souvenir.SouvenirGetResult.record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=487,
)


_SOUVENIRSEARCHQUERY = _descriptor.Descriptor(
  name='SouvenirSearchQuery',
  full_name='souvenir.SouvenirSearchQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='souvenir.SouvenirSearchQuery.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='souvenir.SouvenirSearchQuery.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='souvenir.SouvenirSearchQuery.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre', full_name='souvenir.SouvenirSearchQuery.genre', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=601,
)


_SOUVENIRSEARCHRESULT = _descriptor.Descriptor(
  name='SouvenirSearchResult',
  full_name='souvenir.SouvenirSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='souvenir.SouvenirSearchResult.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=668,
)

_SOUVENIRRECORD.fields_by_name['data'].message_type = _SOUVENIRDATA
_SOUVENIRDATA.fields_by_name['genre'].enum_type = _SOUVENIRGENRE
_SOUVENIRCREATEQUERY.fields_by_name['data'].message_type = _SOUVENIRDATA
_SOUVENIRCREATERESULT.fields_by_name['record'].message_type = _SOUVENIRRECORD
_SOUVENIRGETRESULT.fields_by_name['record'].message_type = _SOUVENIRRECORD
_SOUVENIRSEARCHQUERY.fields_by_name['genre'].enum_type = _SOUVENIRGENRE
_SOUVENIRSEARCHRESULT.fields_by_name['records'].message_type = _SOUVENIRRECORD
DESCRIPTOR.message_types_by_name['SouvenirRecord'] = _SOUVENIRRECORD
DESCRIPTOR.message_types_by_name['SouvenirData'] = _SOUVENIRDATA
DESCRIPTOR.message_types_by_name['SouvenirCreateQuery'] = _SOUVENIRCREATEQUERY
DESCRIPTOR.message_types_by_name['SouvenirCreateResult'] = _SOUVENIRCREATERESULT
DESCRIPTOR.message_types_by_name['SouvenirDeleteQuery'] = _SOUVENIRDELETEQUERY
DESCRIPTOR.message_types_by_name['SouvenirDeleteResult'] = _SOUVENIRDELETERESULT
DESCRIPTOR.message_types_by_name['SouvenirGetQuery'] = _SOUVENIRGETQUERY
DESCRIPTOR.message_types_by_name['SouvenirGetResult'] = _SOUVENIRGETRESULT
DESCRIPTOR.message_types_by_name['SouvenirSearchQuery'] = _SOUVENIRSEARCHQUERY
DESCRIPTOR.message_types_by_name['SouvenirSearchResult'] = _SOUVENIRSEARCHRESULT
DESCRIPTOR.enum_types_by_name['SouvenirGenre'] = _SOUVENIRGENRE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SouvenirRecord = _reflection.GeneratedProtocolMessageType('SouvenirRecord', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRRECORD,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirRecord)
  ))
_sym_db.RegisterMessage(SouvenirRecord)

SouvenirData = _reflection.GeneratedProtocolMessageType('SouvenirData', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRDATA,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirData)
  ))
_sym_db.RegisterMessage(SouvenirData)

SouvenirCreateQuery = _reflection.GeneratedProtocolMessageType('SouvenirCreateQuery', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRCREATEQUERY,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirCreateQuery)
  ))
_sym_db.RegisterMessage(SouvenirCreateQuery)

SouvenirCreateResult = _reflection.GeneratedProtocolMessageType('SouvenirCreateResult', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRCREATERESULT,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirCreateResult)
  ))
_sym_db.RegisterMessage(SouvenirCreateResult)

SouvenirDeleteQuery = _reflection.GeneratedProtocolMessageType('SouvenirDeleteQuery', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRDELETEQUERY,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirDeleteQuery)
  ))
_sym_db.RegisterMessage(SouvenirDeleteQuery)

SouvenirDeleteResult = _reflection.GeneratedProtocolMessageType('SouvenirDeleteResult', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRDELETERESULT,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirDeleteResult)
  ))
_sym_db.RegisterMessage(SouvenirDeleteResult)

SouvenirGetQuery = _reflection.GeneratedProtocolMessageType('SouvenirGetQuery', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRGETQUERY,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirGetQuery)
  ))
_sym_db.RegisterMessage(SouvenirGetQuery)

SouvenirGetResult = _reflection.GeneratedProtocolMessageType('SouvenirGetResult', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRGETRESULT,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirGetResult)
  ))
_sym_db.RegisterMessage(SouvenirGetResult)

SouvenirSearchQuery = _reflection.GeneratedProtocolMessageType('SouvenirSearchQuery', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRSEARCHQUERY,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirSearchQuery)
  ))
_sym_db.RegisterMessage(SouvenirSearchQuery)

SouvenirSearchResult = _reflection.GeneratedProtocolMessageType('SouvenirSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _SOUVENIRSEARCHRESULT,
  __module__ = 'souvenir.messages_pb2'
  # @@protoc_insertion_point(class_scope:souvenir.SouvenirSearchResult)
  ))
_sym_db.RegisterMessage(SouvenirSearchResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
