// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/messages.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coord struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_56bdbdd9dc826ecb, []int{0}
}

func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (m *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(m, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coord) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*Coord)(nil), "common.Coord")
}

func init() { proto.RegisterFile("common/messages.proto", fileDescriptor_56bdbdd9dc826ecb) }

var fileDescriptor_56bdbdd9dc826ecb = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x83, 0x08, 0x2b, 0x39, 0x72, 0xb1, 0x3a, 0xe7, 0xe7, 0x17, 0xa5, 0x08, 0x49,
	0x71, 0x71, 0xe4, 0x24, 0x96, 0x64, 0x96, 0x94, 0xa6, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30,
	0x06, 0xc1, 0xf9, 0x42, 0x32, 0x5c, 0x9c, 0x39, 0xf9, 0x79, 0xe9, 0x10, 0x49, 0x26, 0xb0, 0x24,
	0x42, 0xc0, 0xc9, 0x3a, 0xca, 0x32, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57,
	0xbf, 0xa0, 0x28, 0x3f, 0x35, 0x27, 0xa9, 0x24, 0x4f, 0xbf, 0x38, 0x39, 0x23, 0x3f, 0x3f, 0x47,
	0x37, 0xb5, 0x2c, 0x55, 0x37, 0x2f, 0xb1, 0x2c, 0x53, 0x3f, 0x3d, 0xb1, 0x24, 0xb5, 0x3c, 0xb1,
	0x52, 0x1f, 0x6c, 0x7f, 0xb1, 0x3e, 0xc4, 0xfe, 0x24, 0x36, 0x30, 0xd7, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xa2, 0xee, 0xe6, 0x25, 0xa7, 0x00, 0x00, 0x00,
}
